### ISSUE TITLE
Use .rust-version files to denote directory overrides

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#1049] opened 2017-04-10 04:37 UTC
Could rustup respect `.rust-version` files for directory overrides? This way clearly communicates to users, operators, and version control, which version of Rust is expected for a given project. This trick is used by `chruby` and `nodenv` to signal Ruby and Node.js versions, for example.

**Comment by metajack** [comment] 2017-05-02 17:18
I think this is a dupe of https://github.com/rust-lang-nursery/rustup.rs/issues/460

**Comment by Diggsey** [comment] 2017-05-03 23:13
Closing as dupe

**Closed as completed by Diggsey** 2017-05-03 23:13 UTC
