### ISSUE TITLE
Concurrent installations of a toolchain potentially racy

### ISSUE THREAD

**Issue by retep998** [rust-lang/rustup#2446] opened 2020-08-04 03:00 UTC
We have a CI setup where the builders run on the same machine but are not sandboxed from each other. When updating Rust toolchains this means that the builders can attempt to install the same toolchain concurrently resulting in interesting errors. For example:

```
>rustup target add i686-pc-windows-msvc 
22:39:06 info: syncing channel updates for '1.45.2-x86_64-pc-windows-msvc'
22:39:06 info: latest update on 2020-08-03, rust version 1.45.2 (d3fb005a3 2020-07-31)
22:39:06 info: downloading component 'cargo'
22:39:06 info: downloading component 'clippy'
22:39:06 info: downloading component 'rust-docs'
22:39:08 info: downloading component 'rust-std'
22:39:09 info: downloading component 'rustc'
22:39:13 info: downloading component 'rustfmt'
22:39:13 info: installing component 'cargo'
22:39:13 info: installing component 'clippy'
22:39:13 info: installing component 'rust-docs'
22:39:52 info: installing component 'rust-std'
22:39:52 info: installing component 'rustc'
22:39:54 info: installing component 'rustfmt'
22:39:57 info: downloading component 'rust-std' for 'i686-pc-windows-msvc'
22:40:01 info: installing component 'rust-std' for 'i686-pc-windows-msvc'
```
```
>rustup target add i686-pc-windows-msvc 
22:39:05 info: syncing channel updates for '1.45.2-x86_64-pc-windows-msvc'
22:39:06 info: latest update on 2020-08-03, rust version 1.45.2 (d3fb005a3 2020-07-31)
22:39:06 info: downloading component 'cargo'
22:39:06 info: downloading component 'clippy'
22:39:07 info: downloading component 'rust-docs'
22:39:08 error: component download failed for rust-docs-x86_64-pc-windows-msvc
22:39:08 error: caused by: could not rename file
```

It would probably be better to detect this situation and have one of the rustup invocations wait for the other to finish before proceeding and realizing the toolchain was already installed.

**Comment by rbtcollins** [comment] 2020-08-04 03:02
Duplicate of #988

**Closed as completed by rbtcollins** 2020-08-04 03:02 UTC
Labels: bug
