### ISSUE TITLE
why I cannot use rustfmt on my windows machine ??

### ISSUE THREAD

**Issue by 756445638** [rust-lang/rustup#2651] opened 2021-02-07 01:54 UTC
Output of `rustup --version`:

rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.51.0-nightly (4f4656d46 2021-02-04)`

Output of `rustup show`:

$ rustfmt
error: the 'rustfmt' component which provides the command 'rustfmt.exe' is not available for the 'nightly-x86_64-pc-windows-msvc' toolchain

**Comment by kinnison** [comment] 2021-02-07 09:28
This happens when `nightly` doesn't contain a particular components. https://rust-lang.github.io/rustup-components-history/ suggests `rustfmt` hasn't been available for a while.

If you want the most recent `nightly` which does have the components you desire, then you can do:

```shell
$ rustup toolchain install --allow-downgrade nightly -c rustfmt
```

Either way, this is not a bug in `rustup` unless you've tried that and it didn't do as expected.

Please try that, and assuming all goes well, you can close this issue once you have a `nightly` which works for you.

**Comment by 756445638** [comment] 2021-02-08 05:25
thank you a lot,  I downgrade the toolchain , and worked.

**Closed as completed** 2021-02-09 10:48 UTC
Labels: not-rustup
