### ISSUE TITLE
rustup doc produces an unhelpful error dialog

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rustup#959] opened 2017-02-20 12:10 UTC
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04.2 LTS
Release: 16.04
Codename: xenial

I installed rust using the command in the online manual:

$ curl https://sh.rustup.rs -sSf | sh

This set the path in my .profile file but that doesn't seem to be read even when I open a new console, so I copied the path command into .bashrc and opened a new console:

$ rustc --version
rustc 1.15.1 (021bd29 2017-02-08)

$ rustup doc
This popped up an untitled message box with the following text:

Failed to open "/home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html".
Error when getting information for file '/home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html': No such file or directory.

It would be better if the error message said something like:

The rust documentation isn't installed locally by default.
To read the documentation either go online to doc.rust-lang.org, or install locally by running:
$ rustup component add rust-docs

See https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072

**Comment by bmmoore** [comment] 2017-03-01 20:28
This seems like another manifestation of #901. I don't know why some see a silent failure and some get an error dialog. I suspect the message box here isn't coming from rustup itself but from whatever it's asking to open an html file, with some people's default application failing silently (or at least just not reporting it graphically) instead of complaining.

**Comment by brson** [comment] 2017-03-16 22:39
Thanks for the report @mark-summerfield and @bmmoore !

Looks like a dupe of https://github.com/rust-lang-nursery/rustup.rs/issues/901

**Closed as completed by brson** 2017-03-16 22:39 UTC
