### ISSUE TITLE
misleading error message when you give a partial version number

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustup#882] opened 2016-12-22 21:00 UTC
```shell
> rustup toolchain install 1.13
error: toolchain '1.13' is not installed
> rustup toolchain install 1.13.0
....
```

This confused me for a while. I would have expected something like "1.13 is not a valid toolchain", at minimum, and ideally something like:

```
> rustup toolchain install 1.13
error: '1.13' is not a valid toolchain
Perhaps you meant one of the following?
- 1.13.0
- 1.13.1 // if we had had a point release... :)
```

**Comment by Diggsey** [comment] 2017-05-03 23:25
Alternatively: #794

**Comment by Diggsey** [comment] 2017-05-03 23:26
Dupe of #793

**Closed as completed by Diggsey** 2017-05-03 23:26 UTC
