### ISSUE TITLE
Mac `update --force` panicked at 'components available'

### ISSUE THREAD

**Issue by Nighink** [rust-lang/rustup#1496] opened 2018-09-03 06:16 UTC
The nightly update on my Mac doesn't work due to `error: component 'rls-preview' for 'x86_64-apple-darwin' is unavailable for download`. I then tried to force the update (`update --force`) hoping that this will skip over the rls-preview and install the rest. When doing this, I encountered a panic:

```
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-09-03, rust version 1.30.0-nightly (9395f0af7 2018-09-02)
thread 'main' panicked at 'components available', libcore/option.rs:914:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: rustup_dist::manifestation::Manifestation::update
  10: rustup_dist::dist::update_from_dist_
  11: rustup_dist::dist::update_from_dist
  12: rustup::install::InstallMethod::run
  13: rustup::toolchain::Toolchain::install
  14: rustup::toolchain::Toolchain::install_from_dist_inner
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  16: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  18: rustup::config::Cfg::update_all_channels
  19: rustup_init::common::update_all_channels
  20: rustup_init::rustup_mode::update
  21: rustup_init::rustup_mode::main
  22: rustup_init::main
  23: std::rt::lang_start::{{closure}}
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
  26: std::rt::lang_start_internal
  27: main
```

**Comment by oli-obk** [comment] 2018-11-22 13:04
Still happening:

```
➜  clippy git:(mut_ref) ✗ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-11-22, rust version 1.32.0-nightly (0b9f19dff 2018-11-21)
error: some components unavailable for download: 'clippy-preview', 'rls-preview'
➜  clippy git:(mut_ref) ✗ RUST_BACKTRACE=1 rustup update nightly --force
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-11-22, rust version 1.32.0-nightly (0b9f19dff 2018-11-21)
thread 'main' panicked at 'components available', libcore/option.rs:989:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::option::expect_failed
             at libcore/option.rs:989
   9: rustup_dist::manifestation::Manifestation::update
  10: rustup_dist::dist::update_from_dist_
  11: rustup_dist::dist::update_from_dist
  12: rustup::install::InstallMethod::run
  13: rustup::toolchain::Toolchain::install
  14: rustup::toolchain::Toolchain::install_from_dist_inner
  15: rustup::toolchain::Toolchain::install_from_dist
  16: rustup_init::rustup_mode::update
  17: rustup_init::rustup_mode::main
  18: rustup_init::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  21: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  22: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  23: main
  24: __libc_start_main
  25: <unknown>
```

**Comment by TheIronBorn** [comment] 2018-12-24 03:30
```console
$ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-12-24, rust version 1.33.0-nightly (ddab10a69 2018-12-23)
error: component 'clippy' for target 'x86_64-apple-darwin' is unavailable for download
$ RUST_BACKTRACE=full rustup update nightly --force
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-12-24, rust version 1.33.0-nightly (ddab10a69 2018-12-23)
thread 'main' panicked at 'components available', libcore/option.rs:1008:5
stack backtrace:
   0:        0x10b25db53 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h2a76e18b1b594511
   1:        0x10b2611ca - std::panicking::default_hook::{{closure}}::hccac027f175811b4
   2:        0x10b26018e - std::panicking::rust_panic_with_hook::h11860e91fb60d90b
   3:        0x10b25fc0d - std::panicking::continue_panic_fmt::h28d8e12e50184e99
   4:        0x10b262e98 - rust_begin_unwind
   5:        0x10b26df69 - core::panicking::panic_fmt::hc0099dc0d85edf22
   6:        0x10b26e038 - core::option::expect_failed::hbeb26ea7c79ca417
   7:        0x10afeb3d0 - rustup_dist::manifestation::Manifestation::update::h18064367c5f1363f
   8:        0x10afd94ef - rustup_dist::dist::update_from_dist_::h6e3617f4839cf9b0
   9:        0x10aeee3fa - rustup::toolchain::Toolchain::install::h7d600be62148b62a
  10:        0x10aeed8c9 - rustup::toolchain::Toolchain::install_from_dist_inner::hc8190e1928237425
  11:        0x10aea5691 - rustup_init::rustup_mode::update::h5417760f85e0f852
  12:        0x10ae788c8 - rustup_init::rustup_mode::main::hdb68b690c22233a4
  13:        0x10aec01e5 - rustup_init::run_rustup::h4b18de9a9b2b0ae8
  14:        0x10aebf2f7 - rustup_init::main::h2abcae2aed8102ac
  15:        0x10ae609c5 - std::rt::lang_start::{{closure}}::hce626d554c8170b6
  16:        0x10aec69f4 - main
```

```console
$ rustup --version --verbose
rustup 1.16.0 (beab5ac2b 2018-12-06)

**Comment by CAD97** [comment] 2019-01-21 02:45
Confirmed happening on Windows (same version as above) but with an empty backtrace.

**Comment by kinnison** [comment] 2020-12-03 21:39
The update code has changed significantly since these reports, with no further suggestion of similar issues, I'm going to close this.

If you still encounter this kind of situation please open a fresh issue where we can discuss it.

**Closed as completed by kinnison** 2020-12-03 21:39 UTC
Labels: bug
