### ISSUE TITLE
"rustup component remove [component]" fails if component files do not exist.

### ISSUE THREAD

**Issue by mlsvrts** [rust-lang/rustup#2799] opened 2021-06-18 18:40 UTC
**Problem**
`rustup component remove [component]` fails if component files do not exist. This, incidentally, will also break `rustup update`.

Windows had some issues, and after some repair my recently installed `clippy` executables were deleted. However, rustup was still of the opinion that clippy was installed, preventing me from updating/adding/removing components:

    $ rustup component list | rg clippy
    clippy-x86_64-pc-windows-msvc (installed)
    $ rustup component remove clippy-x86_64-pc-windows-msvc
    info: removing component 'clippy'
    info: rolling back changes
    error: failure removing component 'clippy-preview-x86_64-pc-windows-msvc', directory does not exist: 'bin/cargo-clippy.exe'

**Steps**

Here are the steps to produce this issue with the `clippy` component on windows:
1. Add a component: `rustup component add clippy-preview`
2. Manually delete `C:\Users\[USERNAME]\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo-clippy.exe`
3. Run: `rustup component remove clippy-x86_64-pc-windows-msvc`

**Possible Solution(s)**
To workaround this issue, you can create empty files based on the error output of `rustup component remove [x]` until it succeeds, and then re-install the component.

I think to actually fix this issue, `component remove` should not panic when it tries to delete a file that does not exist, since its goal was to remove that file anyway.

**Notes**

Output of `rustup --version`: `rustup 1.24.3 (ce5817a94 2021-05-31)`
Output of `rustup show`:

    Default host: x86_64-pc-windows-msvc
    rustup home:  C:\Users\[USERNAME]\.rustup
    stable-x86_64-pc-windows-msvc (default)
    rustc 1.53.0 (53cb7b09b 2021-06-17)

**Comment by rbtcollins** [comment] 2021-06-18 19:08
Duplicate of #1480

**Closed as completed by rbtcollins** 2021-06-18 19:08 UTC
Labels: bug
