### ISSUE TITLE
Multiple "warning: could not canonicalize path" at start of any tool invocation

### ISSUE THREAD

**Issue by xaquseg** [rust-lang/rustup#999] opened 2017-03-20 19:15 UTC
Whenever I run any tool (rustup itself, rustc, cargo, seems to impact everything) I get two copies of "warning: could not canonicalize path" for the folder I'm in, and then one for each parent directory, excluding the drive root. This only happens when the current folder is on C:, it doesn't happen for other drives. `println!("{:?}", std::fs::canonicalize(r"C:\Users"))` doesn't error in a test program, but rustup prints an error for that path.

The tools themselves run properly after the warnings print, and directly running the binaries under `.rustup/toolchains/*/bin` doesn't print the warnings.

I'm on Windows 7 64 bit.

**Comment by Diggsey** [comment] 2017-05-04 21:48
Dupe of #682

**Closed as completed by Diggsey** 2017-05-04 21:48 UTC
Labels: bug, help wanted
