### ISSUE TITLE
toolchain is redownloaded when not necessary

### ISSUE THREAD

**Issue by eminence** [rust-lang/rustup#3017] opened 2022-06-24 17:22 UTC
### Problem

When I have a rust-toolchain file that references a toolchain that is already downloaded, it seems like rustup will download it again

### Steps

1. Run `rustup update nightly` to get the latest nightly toolchain:

```text
❯ rustup update nightly
info: syncing channel updates for 'nightly-2022-06-22-x86_64-unknown-linux-gnu'
info: latest update on 2022-06-22, rust version 1.63.0-nightly (dc80ca78b 2022-06-21)
...downloading message elided...

  nightly-x86_64-unknown-linux-gnu updated - rustc 1.63.0-nightly (dc80ca78b 2022-06-21) (from rustc 1.63.0-nightly (ca122c7eb 2022-06-13))
```

2. Create a `rust-toolchain.toml` file that references this same nightly version:

```toml
[toolchain]
channel = "nightly-2022-06-22"
profile = "minimal"
```

3. Run `cargo check` and observe that it redownloads the same nightly version that was downloaded by running `rustup update nightly`

```text
❯ cargo check
info: syncing channel updates for 'nightly-2022-06-22-x86_64-unknown-linux-gnu'
info: latest update on 2022-06-22, rust version 1.63.0-nightly (dc80ca78b 2022-06-21)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
```

(Observe the date and hash are the same `(dc80ca78b 2022-06-21`)

### Rustup version

```console
rustup 1.24.3 (ce5817a94 2021-05-31)
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/achin/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2020-01-06-x86_64-unknown-linux-gnu
nightly-2020-01-08-x86_64-unknown-linux-gnu
nightly-2020-01-09-x86_64-unknown-linux-gnu
nightly-2020-01-10-x86_64-unknown-linux-gnu
nightly-2020-01-13-x86_64-unknown-linux-gnu
nightly-2020-01-14-x86_64-unknown-linux-gnu
nightly-2020-03-31-x86_64-unknown-linux-gnu
nightly-2020-04-13-x86_64-unknown-linux-gnu
nightly-2020-04-23-x86_64-unknown-linux-gnu
nightly-2020-07-01-x86_64-unknown-linux-gnu
nightly-2020-09-29-x86_64-unknown-linux-gnu
nightly-2020-10-19-x86_64-unknown-linux-gnu
nightly-2021-11-12-x86_64-unknown-linux-gnu
nightly-2021-12-15-x86_64-unknown-linux-gnu
nightly-2021-12-16-x86_64-unknown-linux-gnu
nightly-2022-04-29-x86_64-unknown-linux-gnu
nightly-2022-06-21-x86_64-unknown-linux-gnu
nightly-2022-06-22-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
1.10-x86_64-unknown-linux-gnu
1.13-x86_64-unknown-linux-gnu
1.14-x86_64-unknown-linux-gnu
1.15-x86_64-unknown-linux-gnu
1.31-x86_64-unknown-linux-gnu
1.34-x86_64-unknown-linux-gnu
1.35-x86_64-unknown-linux-gnu
1.38-x86_64-unknown-linux-gnu
1.39-x86_64-unknown-linux-gnu
1.40-x86_64-unknown-linux-gnu
1.41-x86_64-unknown-linux-gnu
1.42-x86_64-unknown-linux-gnu
1.43-x86_64-unknown-linux-gnu
1.48-x86_64-unknown-linux-gnu
1.55-x86_64-unknown-linux-gnu
1.56-x86_64-unknown-linux-gnu
1.8-x86_64-unknown-linux-gnu
1.0.0-x86_64-unknown-linux-gnu
1.14.0-x86_64-unknown-linux-gnu
1.30.0-x86_64-unknown-linux-gnu
1.31.0-x86_64-unknown-linux-gnu
1.32.0-x86_64-unknown-linux-gnu
1.33.0-x86_64-unknown-linux-gnu
1.34.0-x86_64-unknown-linux-gnu
1.35.0-x86_64-unknown-linux-gnu
1.36.0-x86_64-unknown-linux-gnu
1.37.0-x86_64-unknown-linux-gnu
1.38.0-x86_64-unknown-linux-gnu
1.40.0-x86_64-unknown-linux-gnu
1.41.0-x86_64-unknown-linux-gnu
1.42.0-x86_64-unknown-linux-gnu
1.48.0-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2022-06-22-x86_64-unknown-linux-gnu (overridden by '/home/achin/tmp/69/foo/rust-toolchain.toml')
rustc 1.63.0-nightly (dc80ca78b 2022-06-21)
```

**Comment by rbtcollins** [comment] 2022-06-24 21:22
This is already discussed in other bugs. The fundamental aspect here is that nightly is not the same as nightly-date, and rustup doesn't know about whether nightly from-a-particular date satisfies nightly-date.

I recommend against using toolchain files unless you have a specific need for them - they are not transitive, so other crates depending on yours will not honour them. They are most useful for the very specific use case of building custom rust toolchains for new platforms / inhouse patches to rust, and for some parts of the rust build process.

I'm going to close this because as I mention I'm 99% sure it is a duplicate of another open bug. if its not please reopen it / let me know to reopen it, as I think the idea of supporting nightly satisfying a particular nightly-XXX is not harmful

**Closed as completed by rbtcollins** 2022-06-24 21:22 UTC
Labels: bug
