### ISSUE TITLE
Teach manifests about optional but default components

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#905] opened 2017-01-06 00:53 UTC
Right now the manifest format has required components, installed by default, and optional components, not installed by default. rust-docs though want to be optional, but installed by default.

cc https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072/20

**Comment by Diggsey** [comment] 2017-05-11 22:30
This is a duplicate of #1006

**Closed as completed by Diggsey** 2017-05-11 22:30 UTC
