### ISSUE TITLE
rust-analyzer is not being automatically proxied after installing

### ISSUE THREAD

**Issue by Cavig01** [rust-lang/rustup#3801] opened 2024-05-01 08:37 UTC
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

Just as in the title.
Both belonging to `DUP_TOOLS`, rustfmt doesn't seem to have the problem. Why?

### Steps

`$ rustup component add rust-analyzer` and 
`$ rust-analyzer`, you'll get:
```
bash: rust-analyzer: command not found
```

### Rustup version

```console
rustup 1.27.0 (2024-03-12)
```

### Installed toolchains

```console
Default host: aarch64-unknown-linux-gnu
rustup home:  /root/.rustup

stable-aarch64-unknown-linux-gnu (default)
rustc 1.77.2 (25ef9e3d8 2024-04-09)
```

### OS version

```console
Arch Linux
```

**Comment by rami3l** [comment] 2024-05-01 10:30
@Cavig01 It seems that I cannot reproduce this issue on my ARM64 Mac:

```console
> docker run --rm -it ubuntu

root@5a5f7c31c016:/# uname -a
Linux 5a5f7c31c016 6.8.4-200.fc39.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Apr  4 21:00:27 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

[installing `curl`...]

root@5a5f7c31c016:/# curl -sSf https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh | sh
info: downloading installer
[...]
info: default toolchain set to 'stable-aarch64-unknown-linux-gnu'

  stable-aarch64-unknown-linux-gnu installed - rustc 1.77.2 (25ef9e3d8 2024-04-09)
[...]

root@5a5f7c31c016:/# . ~/.cargo/env 

root@5a5f7c31c016:/# rustup component add rust-analyzer
info: downloading component 'rust-analyzer'
info: installing component 'rust-analyzer'

root@5a5f7c31c016:/# which rust-analyzer
/root/.cargo/bin/rust-analyzer

root@5a5f7c31c016:/# rust-analyzer --version
rust-analyzer 1.77.2 (25ef9e3d 2024-04-09)
```

Did you do anything special?

**Comment by Cavig01** [comment] 2024-05-02 15:27
@rami3l I've just tried. It appears that it was because I installed rustup by pacman. Rustup installed by `rustup-init.sh` doesn't have the problem.

**Comment by rami3l** [comment] 2024-05-02 15:40
@Cavig01 Thanks for the investigation! This could be an interesting issue to be reported to the package maintainers then.

Since there's really not much we can do on our side, I'm closing this issue. Please feel free to contact us if you have other questions!

**Closed as not planned by rami3l** 2024-05-02 15:40 UTC
Labels: not-rustup

**Comment by Cavig01** [comment] 2024-05-03 08:08
I've found the cause. In case whoever else meet this problem:
This is an intentional design on the pacman package `rustup`. It's not that `rust-analyzer` isn't being proxied, but proxied at `/usr/lib/rustup/bin/rust-analyzer`. It was to avoid conflict between `rust-analyzer` installed by rustup and one by pacman, since it is also an available pacman package.

To solve this problem, you can just add `/usr/lib/rustup/bin/` in your `$PATH` variable.
