### ISSUE TITLE
Panic while installing cargo

### ISSUE THREAD

**Issue by tage64** [rust-lang/rustup#2256] opened 2020-03-09 08:31 UTC
**Problem**

Rustup panics while trying to install a toolchain during the installation of cargo.

**Steps**

```
$ rustup install stable
```

Gives the following output:

```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-02-27, rust version 1.41.1 (f3e1a954d 2020-02-24)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:172:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: __libc_start_main
  20: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
info: rolling back changes
```

**Notes**

Output of `rustup --version`:
rustup 1.21.1 (2020-02-23)

Output of `rustup show`:
Default host: x86_64-unknown-linux-gnu
rustup home:  <path>

no active toolchain

I'm using arch linux under wsl.

**Comment by kinnison** [comment] 2020-03-09 08:48
This is a bug in arch linux's glibc vs. wsl1

Duplicate of #2245

**Closed as completed by kinnison** 2020-03-09 08:48 UTC
Labels: bug
