### ISSUE TITLE
Allow specifying overrides locally?

### ISSUE THREAD

**Issue by bronson** [rust-lang/rustup#827] opened 2016-11-21 22:46 UTC
Right now, rustup stores its overrides in `~/.multirust/settings.toml`.

If I rename my directory, or move it elsewhere, the overrides don't follow.  Also, when our team updates the rust version for a particular project, we need to send out an email telling everyone to update their overrides, bringing problems cause by out-of-band communication.

These issues would go away if overrides could be stored in a project-local file (maybe ./rust-version, similar to [.ruby-version](https://gist.github.com/fnichol/1912050)?)

Has this been considered before?  Thanks.

**Comment by Diggsey** [comment] 2016-11-21 22:57
Something similar was brought up before. At the time I was against it because I didn't want to see people pinning specific compiler host triples to their projects, and making life difficult for people trying to just build it.

The other factor was that the stable compiler should be... stable, so it's unclear whether that should be handled by rustup, or by cargo (say by depending on at least a certain libstd version).

However, another important case is pinning a specific *version* of nightly, without pinning the host triple, which is quite important for development against nightly where there are frequent breakages. I'd be in favour of something like that, maybe with precedence lower than the existing override system, so that it's still easy to bypass if need be.

**Comment by bronson** [comment] 2016-11-21 23:47
That's true, the architecture would need to stay out of the file.  I hadn't noticed that.

So the .rust-version file would contain something like `nightly-2016-11-06`...  And, agreed, `rustup override` would override any rust-version files.

A whole new dependency hell could be created where crates are all specifying different compilers,  but I think the rust community will naturally avoid that.  Heck, if you're publishing a crate with a .rust-version with anything other than `nightly`, something's amiss.

That sounds great.  I'd submit a PR, but I need to learn Rust first...

**Comment by metajack** [comment] 2017-05-02 17:18
This is a dupe of https://github.com/rust-lang-nursery/rustup.rs/issues/460

**Comment by Diggsey** [comment] 2017-05-03 23:12
Closing in favour of #460

**Closed as completed by Diggsey** 2017-05-03 23:12 UTC
