### ISSUE TITLE
PATH doesn't work on macOS Sierra

### ISSUE THREAD

**Issue by sinhpham** [rust-lang/rustup#868] opened 2016-12-17 17:31 UTC
rustup.rs adds the ~/.cargo/bin path to ~/.profile, however on my macbook with Sierra that file doesn't seem to work. I have to manually add the path to ~./.bash_profile

**Comment by emilebres** [comment] 2016-12-27 09:27
It's rather that `.profile` is not read if `.bash_profile` exists.

From bash's manual
```
it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.
```

**Comment by Diggsey** [comment] 2017-05-03 23:46
Dupe of #758

**Closed as completed by Diggsey** 2017-05-03 23:46 UTC
