### ISSUE TITLE
Installing on Ubuntu 20.04 WSL results in a crash

### ISSUE THREAD

**Issue by krojew** [rust-lang/rustup#2323] opened 2020-05-08 07:57 UTC
**Problem**
Downloading and installing components on latest WSL Ubuntu results in:

```
info: installing component 'cargo'
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
stack backtrace:
   0:     0x7ff050cdbc9c - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x7ff050cdbc9c - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x7ff050cdbc9c - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7ff050cdbc9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7ff0509ba81c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7ff050cdb526 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x7ff050cdb19e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7ff050cdb19e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7ff050cdb19e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x7ff050cda943 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x7ff050cda943 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x7ff050cda4be - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x7ff050cda450 - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x7ff050caae86 - <rustup::diskio::threaded::Threaded as rustup::diskio::Executor>::join::hf33124263a81d2a4
  14:     0x7ff050caa636 - core::ptr::real_drop_in_place::haa8255139d9471a2
  15:     0x7ff0509d5190 - core::ptr::real_drop_in_place::h04c627b98e68397b
  16:     0x7ff050c9e777 - rustup::dist::component::package::unpack_without_first_dir::h352b57d236248e9a
  17:     0x7ff050c762f6 - rustup::dist::manifestation::Manifestation::update::h8c800deec8167b5b
  18:     0x7ff050c64b8a - rustup::dist::dist::try_update_from_dist_::h113375517e7a85ca
  19:     0x7ff050c4964c - rustup::toolchain::Toolchain::install::h048b51ffab245b48
  20:     0x7ff050c46c8c - rustup::toolchain::Toolchain::install_from_dist::h00b9aafeb93470e5
  21:     0x7ff0509143ee - rustup_init::self_update::install::h4cee0e396cee456b
  22:     0x7ff050925ca2 - rustup_init::run_rustup_inner::ha545371fd2dc19a6
  23:     0x7ff050922d64 - rustup_init::main::hba9a23e308c96901
  24:     0x7ff0508b7a03 - std::rt::lang_start::{{closure}}::h1778d9ce6385bef5
  25:     0x7ff05092c458 - main
  26:     0x7ff0503e70b3 - __libc_start_main
  27:     0x7ff0508b4029 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

**Steps**
1. Install latest Ubuntu on Windows 10.
2. Try to install Rust using official instructions.

**Comment by kinnison** [comment] 2020-05-08 09:41
Dupe of #2319 which is itself a dupe of #2245

**Comment by kinnison** [comment] 2020-05-08 09:41
In summary, in case people find this particular issue - this is a bug in glibc+WSL and nothing we can fix in Rustup itself.

**Closed as completed by kinnison** 2020-05-08 09:41 UTC
Labels: bug

**Comment by steelx** [comment] 2020-06-11 04:04
`sudo apt --fix-broken install` & then
the only working way so far is `brew install rust`
