### ISSUE TITLE
rustup default nightly fails on windows

### ISSUE THREAD

**Issue by iCrawl** [rust-lang/rustup#1096] opened 2017-05-05 22:47 UTC
It seems like `rustup default nightly` simply won't install correctly on my windows system? I tried searching for any issues about it, but none of them mentioned the same error I am experiencing.

If it's my mistake, I'm very sorry but for now I can't seem to find out why its not normalizing paths (that's what it looks like to me at least).

Running the usual Windows 10 Creators Update in Powershell.

Nightly:
```
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: rolling back changes
error: failed to extract package
info: caused by: failed to unpack `rustc-nightly-x86_64-pc-windows-msvc/rustc/share/man/man1/rustdoc.1` into `C:\Users\Crawl\.rustup\tmp\exc5oyd56ob6gpr9_dir\rustc/share/man/man1/rustdoc.1`
info: caused by: The system cannot find the path specified. (os error 3)
```

Stable:
```
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: downloading component 'rustc'
 33.2 MiB /  33.2 MiB (100 %)  12.4 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 44.7 MiB /  44.7 MiB (100 %)  14.7 MiB/s ETA:   0 s
info: downloading component 'cargo'
info: downloading component 'rust-docs'
  9.9 MiB /   9.9 MiB (100 %)   8.9 MiB/s ETA:   0 s
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: default toolchain set to 'stable-x86_64-pc-windows-msvc'

  stable-x86_64-pc-windows-msvc installed - rustc 1.17.0 (56124baa9 2017-04-24)
```

**Comment by FaultyRAM** [comment] 2017-05-05 22:54
Looks like a duplicate of https://github.com/rust-lang-nursery/rustup.rs/issues/1092

**Comment by iCrawl** [comment] 2017-05-05 22:56
I read that, but I wasn't too sure about it, if it is a collab/owner can feel free to close this.

**Closed as completed** 2017-05-05 23:22 UTC
