### ISSUE TITLE
Bad nightly source tarball (contained a symlink)

### ISSUE THREAD

**Issue by conikeec** [rust-lang/rustup#2434] opened 2020-07-21 02:41 UTC
**Problem**
Receiving an error on update (stable/nightly) leading to rollback

**Steps**
❯ rustup update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2020-07-21, rust version 1.47.0-nightly (f9a308636 2020-07-20)
info: downloading component 'rust-analysis'
info: downloading component 'rust-src'
info: downloading component 'rustc'
 48.1 MiB /  48.1 MiB (100 %)  43.6 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: removing previous version of component 'rust-analysis'
info: removing previous version of component 'rust-src'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'cargo'
info: removing previous version of component 'rust-docs'
info: installing component 'rust-analysis'
info: Defaulting to 500.0 MiB unpack ram
info: installing component 'rust-src'
info: rolling back changes
error: could not rename component file from '/Users/chetanconikee/.rustup/tmp/gx57en2l_r5p93hz_dir/bk' to '/Users/chetanconikee/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin'
error: tar entry kind 'Symlink' is not supported
info: checking for self-updates

       stable-x86_64-apple-darwin unchanged - rustc 1.45.0 (5c1f21c3b 2020-07-13)
  nightly-x86_64-apple-darwin update failed - rustc 1.47.0-nightly (d7f945163 2020-07-19)

info: cleaning up downloads & tmp directories

**Comment by dodheim** [comment] 2020-07-21 03:01
Likewise on Win10 x64 (MSVC ABI, if it matters).

**Comment by rbtcollins** [comment] 2020-07-21 03:49
This looks like toolchains have started including symlinks, which they only
can on some platforms, and definitely not on windows, so I think we should
reassign this bug to rust itself.

**Comment by phil-opp** [comment] 2020-07-21 06:11
There's already a PR to fix this at https://github.com/rust-lang/rust/pull/74578

**Comment by highway900** [comment] 2020-07-21 10:08
I am also seeing this on linux (Ubuntu 18.04)

**Comment by hamaluik** [comment] 2020-07-21 14:58
Just ran into this as well on Manjaro 20.0.3

**Comment by dvdplm** [comment] 2020-07-21 15:48
Seen on macOS 10.15.6

**Comment by kinnison** [comment] 2020-07-21 15:51
It's not surprising, it's a bug in the channel generation, not a bug in Rustup.  See https://github.com/rust-lang/rustup/issues/2434#issuecomment-661655854

**Comment by conikeec** [comment] 2020-07-22 06:01
Seems like https://github.com/rust-lang/rust/pull/74578 is merged to master and yet I see failures on update

```
 12.8 MiB /  12.8 MiB (100 %)   2.7 MiB/s in  4s ETA:  0s
info: removing previous version of component 'rust-analysis'
info: removing previous version of component 'rust-src'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'cargo'
info: removing previous version of component 'rust-docs'
info: installing component 'rust-analysis'
info: Defaulting to 500.0 MiB unpack ram
info: installing component 'rust-src'
info: rolling back changes
error: could not rename component file from '/Users/xxx/.rustup/tmp/uq2qki3860ngfh1s_dir/bk' to '/Users/xxx/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin'
error: tar entry kind 'Symlink' is not supported
info: checking for self-updates

       stable-x86_64-apple-darwin unchanged - rustc 1.45.0 (5c1f21c3b 2020-07-13)
  nightly-x86_64-apple-darwin update failed - rustc 1.47.0-nightly (d7f945163 2020-07-19)

info: cleaning up downloads & tmp directories
```

**Comment by birkenfeld** [comment] 2020-07-22 06:06
It was merged like 10 minutes ago, what do you expect? Nightlies are built once a day - well, night :).

**Comment by kinnison** [comment] 2020-07-22 07:13
Also you can expect to encounter this if the next few nightlys lack a component you depend on, unless you remove those components, rustup will be unable to update nightly until it has everything you need.

**Comment by eddyb** [comment] 2020-07-22 10:38
> Nightlies are built once a day - well, night :).

More accurately, around midnight GMT/UTC (not exactly sure what timezone) the last PR that landed is promoted to "nightly".
(Effectively every time we merge a PR we build a "nightly" from it - [`rustup-toolchain-install-master`](https://github.com/kennytm/rustup-toolchain-install-master) lets you install any PR build, although I believe we delete old ones after a number of days. you could use it to test that the bug is fixed, maybe?)

So you have to wait another 13h-14h or so before a new nightly is published.

**Comment by rbtcollins** [comment] 2020-08-04 03:06
This was fixed in rust itself

**Closed as completed by rbtcollins** 2020-08-04 03:06 UTC
Labels: bug
