### ISSUE TITLE
The docs at rust-lang.github.io/rustup are from master

### ISSUE THREAD

**Issue by winksaville** [rust-lang/rustup#2720] opened 2021-04-14 18:46 UTC
**Problem**
I was reading the [rustup/docs the-toolchain-file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)
section and tried to use `rust-toolchain.toml` but it didn't work. As it turns out support for `.toml` was added after
the 1.23.1 release.

**Steps**
The second paragraph in [rustup/docs the-toolchain-file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) current reads, which is from master as of today:

> "In these cases the toolchain can be named in the project's directory in a file
> called `rust-toolchain.toml` or `rust-toolchain`. If both files are present in
> a directory, the latter is used for backwards compatibility. The files use the
> [TOML] format and have the following layout:"

But the same paragraph from 1.23.1 reads:

> "In these cases the toolchain can be named in the project's directory in a file
> called `rust-toolchain`, the content of which is either the name of a single
> `rustup` toolchain, or a TOML file with the following layout:

**Possible Solution(s)**
Only publish the latest release

**Notes**
Output of cat rust-toolchain:
```
$ cat rust-toolchain
[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc-dev" ]
profile = "minimal"
```
Output of `rustup --version`:
```
$ rustup --version
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.51.0 (2fd73fabe 2021-03-23)`
```
Output of `rustup show`:
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/wink/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2021-03-25-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

thumbv7em-none-eabihf
thumbv7m-none-eabi
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (overridden by '/home/wink/prgs/rust/projects/binance-auto-sell/rust-toolchain')
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**Comment by kinnison** [comment] 2021-04-14 19:13
This is not a bug per-se - the issue is that we're staging a new release and unfortunately because we're taking our time over it, the docs were updated prematurely.  1.24.0 is slated for release in the next little while so the docs will align again at that point.  After that I'll look into whether we can make the doc-update a manual step rather than always happening on pushes to our stable staging branch.

**Comment by winksaville** [comment] 2021-04-14 19:35
I would like to suggest the docs be updated when the "release" actually happens, hopefully that can be automatic. I tend to like having file extensions when possible and glad to see a new release is eminent so I can use `rust-toolchain.toml` :)

**Comment by rbtcollins** [comment] 2021-04-15 07:00
The technical interactions here are as follows.

Releasing is a highly manual process taking an extended period to complete.
The release branch exists to to make the code visible, allow fix PRs to be targeted,  etc.
Such fix PRs are often needed as part of the release process.
The docs come from the release branch, as part of reducing the manual overhead of that release process.

**Comment by kinnison** [comment] 2021-04-29 16:32
For now, I'm going to close this.  We'll have a wider discussion about beta testing which will include documentation.  1.24.1 is now out.

**Closed as completed by kinnison** 2021-04-29 16:32 UTC
Labels: fixed-next-release
