### ISSUE TITLE
Can't install on Android via Termux

### ISSUE THREAD

**Issue by victorgeel** [rust-lang/rustup#3420] opened 2023-07-27 17:22 UTC
(8ede3aae2 2023-07-12)
error: target 'armv7-linux-androideabi' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets

**Comment by rami3l** [comment] 2023-08-07 02:01
Could you please provide some more details on how to reproduce this error, for example, by executing what `rustup` command on which platform? Thanks a lot!

**Comment by kLiHz** [comment] 2023-08-12 10:25
As shown in <https://doc.rust-lang.org/nightly/rustc/platform-support.html>, the rust do have no host toolchain for `armv7-linux-androideabi`. By the way, are you trying to run `rustup` on Android phones via Termux?

**Comment by rbtcollins** [comment] 2023-08-13 18:51
Until the platform has published toolchains, rustup cannot install toolchains for the platform.

If that target is the right target for your environment, then rustup has correctly detected it and the problem is its support level.

If the target is the wrong target for your environment, then rustup needs to be changed to detect it differently.

**Comment by rami3l** [comment] 2024-05-03 00:08
Closing this as a duplicate of #2872 for now.

**Closed as not planned** 2024-05-03 00:07 UTC
Labels: incomplete

**Comment by victorgeel** [comment] 2024-05-06 16:03
> Could you please provide some more details on how to reproduce this error, for example, by executing what `rustup` command on which platform? Thanks a lot!



> Could you please provide some more details on how to reproduce this error, for example, by executing what `rustup` command on which platform? Thanks a lot!

I got solved 
tested on Termux android os.
Thanks !!
