### ISSUE TITLE
If instalation fails preserve download and temp directories, to avoid having to re download installers

### ISSUE THREAD

**Issue by apps4uco** [rust-lang/rustup#4101] opened 2024-11-29 01:15 UTC
### Problem you are trying to solve

# Actual Behaviour 

If the disk fills after download but before instalation, the download and temp directories get cleaned up and all files have to be downloaded again.

# Console 

(excerpt, complete file attached) 

```
...
error: could not rename component file from '/Users/andy/.rustup/tmp/ekec5z_22k0ygyh5_dir/bk' to '/Users/andy/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu'
error: failed to extract package
info: checking for self-update

       stable-aarch64-apple-darwin update failed - rustc 1.80.1 (3f5fd8dd4 2024-08-06)
      nightly-aarch64-apple-darwin update failed - rustc 1.82.0-nightly (4074d4902 2024-08-23)
  nightly-x86_64-unknown-linux-gnu update failed - (error reading rustc version)

info: cleaning up downloads & tmp directories

❯ rustup update
info: syncing channel updates for 'stable-aarch64-apple-darwin'
...
```

### Solution you'd like

# Expected Behaviour

It would be nice if the downloads could be saved, possibly with a message:

```
Install failed due to lack of disk space, please ensure you have at least X GB free space and run 
$ rustup update

or alternatively clean up the tmp and download directories using
$ rustup clean
```

# Test

This could be replicated in a docker container with a limited volume size.

### Notes

[log.txt](https://github.com/user-attachments/files/17953283/log.txt)

**Comment by rami3l** [comment] 2024-11-29 01:44
Duplicate of #3776.

**Closed as not planned by rami3l** 2024-11-29 01:44 UTC
Labels: enhancement
