### ISSUE TITLE
Windows CI installs more than minimal profile

### ISSUE THREAD

**Issue by bluss** [rust-lang/rustup#3738] opened 2024-03-24 17:54 UTC
### Problem

Hey, I found this issue in github actions / CI - i don't otherwise use rustup on windows, so I don't know if this is a known behaviour.

Using `rustup toolchain install stable --profile minimal --no-self-update`  is installing clippy and rustfmt, that doesn't seem like a minimal profile?

### Steps

1. Using dtolnay/rust-toolchain@master in github actions
2. Workflow file https://github.com/bluss/pyproject-local-kernel/actions/runs/8410733408/workflow  relevant part: tests-windows using dtolnay/rust-toolchain@master
3. Workflow run https://github.com/bluss/pyproject-local-kernel/actions/runs/8410733408/job/23029524321

### Notes

Install log details components it's installing

```
2024-03-24T16:42:27.2252966Z ##[group]Run rustup toolchain install stable --profile minimal --no-self-update
2024-03-24T16:42:27.2253610Z [36;1mrustup toolchain install stable --profile minimal --no-self-update[0m
2024-03-24T16:42:27.2264461Z shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
2024-03-24T16:42:27.2264930Z env:
2024-03-24T16:42:27.2265110Z   IS_WINDOWS: 1
2024-03-24T16:42:27.2265324Z ##[endgroup]
2024-03-24T16:42:31.0347401Z info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
2024-03-24T16:42:31.2804450Z info: latest update on 2024-03-21, rust version 1.77.0 (aedd173a2 2024-03-17)
2024-03-24T16:42:31.3071696Z info: downloading component 'clippy'
2024-03-24T16:42:31.3514460Z info: downloading component 'rustfmt'
2024-03-24T16:42:31.3877478Z info: downloading component 'rust-std' for 'x86_64-pc-windows-gnu'
2024-03-24T16:42:31.5770929Z info: downloading component 'rust-std' for 'i686-pc-windows-msvc'
2024-03-24T16:42:31.7326962Z info: downloading component 'cargo'
2024-03-24T16:42:31.8066557Z info: downloading component 'rust-std'
2024-03-24T16:42:32.0286540Z info: downloading component 'rustc'
2024-03-24T16:42:32.9822555Z info: removing previous version of component 'clippy'
2024-03-24T16:42:33.0712838Z info: removing previous version of component 'rustfmt'
2024-03-24T16:42:33.0894244Z info: removing previous version of component 'rust-std' for 'x86_64-pc-windows-gnu'
2024-03-24T16:42:33.1418836Z info: removing previous version of component 'rust-std' for 'i686-pc-windows-msvc'
2024-03-24T16:42:33.1761092Z info: removing previous version of component 'cargo'
2024-03-24T16:42:33.2652728Z info: removing previous version of component 'rust-std'
2024-03-24T16:42:33.3145340Z info: removing previous version of component 'rustc'
2024-03-24T16:42:33.3757858Z info: installing component 'clippy'
2024-03-24T16:42:33.6375647Z info: installing component 'rustfmt'
2024-03-24T16:42:33.8605877Z info: installing component 'rust-std' for 'x86_64-pc-windows-gnu'
2024-03-24T16:42:36.4854953Z info: installing component 'rust-std' for 'i686-pc-windows-msvc'
2024-03-24T16:42:37.7814407Z info: installing component 'cargo'
2024-03-24T16:42:38.3383942Z info: installing component 'rust-std'
2024-03-24T16:42:39.7265799Z info: installing component 'rustc'
```

### Rustup version

```console
rustup 1.27.0 (bbb9276d2 2024-03-08)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.77.0 (aedd173a2 2024-03-17)`
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\runneradmin\.rustup
installed targets for active toolchain
--------------------------------------
i686-pc-windows-msvc
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
active toolchain
----------------
stable-x86_64-pc-windows-msvc (default)
rustc 1.77.0 (aedd173a2 2024-03-17)



(This output from another workflow run https://github.com/bluss/pyproject-local-kernel/actions/runs/8411099546/job/23030300765 )
```

**Comment by djc** [comment] 2024-03-24 18:25
Is this a duplicate of #3709?

**Comment by bluss** [comment] 2024-03-24 18:28
It's not duplicating that issue in any way that I can see at least. In my case there is no error or failure, it installs and runs, just installs too many components.

**Comment by rami3l** [comment] 2024-03-24 23:10
@bluss The thing here is that GitHub Actions has Rustup preinstalled with stable Rust minimal + Rustfmt + Clippy (https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#packages), so I'll say it's not really an actionable thing on our side.

And yes, if you have `stable` preinstalled then specifying a smaller profile while updating is a no-op.

**Comment by bluss** [comment] 2024-03-24 23:24
Oh, that's a reasonable explanation, thanks for the pointer. I'm fine with closing this then if you want to.

**Closed as not planned** 2024-03-24 23:25 UTC
Labels: bug
