### ISSUE TITLE
Fail to update or install after uninstall on Linux

### ISSUE THREAD

**Issue by ncihnegn** [rust-lang/rustup#1592] opened 2018-12-25 09:39 UTC
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-12-25, rust version 1.33.0-nightly (f960f377f 2018-12-24)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: rolling back changes
error: failed to install component: 'rust-std-x86_64-unknown-linux-gnu', detected conflict: '"lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-8svn.so"'

**Comment by daubaris** [comment] 2018-12-25 10:13
Can reproduce. While investigating further it seems that it tries to rename files (directories?) when there are no files in tmp folder.

```error: could not rename component file from '~/.rustup/tmp/sux1ie4v37t3lhck_dir/bk' to ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share'
error: could not rename component file from '~/.rustup/tmp/2zeb7e3cai7jyb70_dir/bk' to ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc'
error: could not rename component file from '~/.rustup/tmp/zrv312f0fx9o1pse_dir/bk' to '~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/man'
error: could not rename component file from ~/.rustup/tmp/7hu9xs_6dmn72_ln_dir/bk' to ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu'
```

`ls -a ~/.rustup/tmp`   shows an empty folder

Not quite sure if they are added only during the update.

**Comment by jbg** [comment] 2018-12-25 11:15
This just started happening on a CI setup of mine. Last successful build was 2018-12-24 16:23 UTC.

`debian:latest` docker image, and then:
```
curl https://sh.rustup.rs -sSf -o /tmp/rustup-init.sh
sh /tmp/rustup-init.sh -y --default-toolchain nightly
```

fails with:
```
Step #0: info: latest update on 2018-12-25, rust version 1.33.0-nightly (f960f377f 2018-12-24)
Step #0: info: downloading component 'rustc'
Step #0: info: downloading component 'rust-std'
Step #0: info: downloading component 'cargo'
Step #0: info: downloading component 'rust-docs'
Step #0: info: installing component 'rustc'
Step #0: info: installing component 'rust-std'
Step #0: info: rolling back changes
Step #0: error: failed to install component: 'rust-std-x86_64-unknown-linux-gnu', detected conflict: '"lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-8svn.so"'
```

**Comment by jbg** [comment] 2018-12-25 11:17
appears to be a duplicate of https://github.com/rust-lang/rustup.rs/issues/1590

**Comment by matthiaskrgr** [comment] 2018-12-27 10:34
I think this is a duplicate of https://github.com/rust-lang/rust/issues/57111 which has been addressed.

**Closed as completed** 2019-04-03 15:04 UTC
