### ISSUE TITLE
progress bar overly precise

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rustup#1743] opened 2019-04-08 22:47 UTC
**Problem**

The progress bar during installation can be overly precise like so:
`3.1 MiB /  10.4 MiB ( 30 %)  46.4 KiB/s ETA: 2.6780612989403734 min 40.68367793642241 s`
I would expect instead to see something like:
`3.1 MiB /  10.4 MiB ( 30 %)  46.4 KiB/s ETA: 2min 40s`

**Steps**

1. Install nightly on Windows (See #904 )
2.
3.

**Possible Solution(s)**

**Notes**

Output of `rustup --version`: `rustup 1.17.0 (069c88ed6 2019-03-05)`
Output of `rustup show`: ```
rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by kinnison** [comment] 2019-04-09 07:02
This is a duplicate of #1696 and #1731 and was fixed in #1699 - the fix will be in rustup 1.18.0

**Closed as completed by kinnison** 2019-04-09 07:02 UTC
Labels: bug
