### ISSUE TITLE
Message is hard to read on a white background

### ISSUE THREAD

**Issue by ayosec** [rust-lang/rustup#888] opened 2016-12-27 02:32 UTC
The message header printed after a successful installation is using white (gray) as the foreground color, which is hard to read in a white background. ([Example](https://cloud.githubusercontent.com/assets/37484/21488866/76a45856-cbdc-11e6-83d4-43851260648a.png))

**Comment by Diggsey** [comment] 2017-05-03 23:29
Dupe of #789

**Closed as completed by Diggsey** 2017-05-03 23:29 UTC
