### ISSUE TITLE
Regression of rustup doc BROWSER environment variable support in #1287

### ISSUE THREAD

**Issue by jer-irl** [rust-lang/rustup#2642] opened 2021-01-21 16:40 UTC
**Problem**

Bug #1287 and PR #1289 added support for the `BROWSER` environment variable to allow overrides to the XDG default browser when running `rustup doc`.

**Steps**

1. `BROWSER=$(some-non-default) rustup doc`
2. Documentation opened in XDG default browser

**Possible Solution(s)**

It looks to me like this feature was reverted with the move to `opener` in this commit e661fc61a3b49a985501d47d2d28b3ae7d1ee19c

It looks like cargo still handles this environment variable and just falls back to `opener` https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_doc.rs#L101 .  Would PRs to restore this feature be welcome?  I'd imagine it would be pretty small and self-contained.

**Notes**

Output of `rustup --version`: ```cargo 1.49.0 (d00d64df9 2020-12-05)```
Output of `rustup show`: 
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/jeremy/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Comment by kinnison** [comment] 2021-01-21 18:07
While I concur that this is a regression, I wonder if the right answer is to push the handling of `BROWSER` into the `opener` crate, rather than duplicating logic between here and Cargo.

 @Seeker14491 how would you feel about `BROWSER` environment variable handling being pushed into `opener` as per the linked approach in Cargo?

**Comment by Seeker14491** [comment] 2021-01-26 02:31
Having the `BROWSER` override implemented in `opener` is planned for the next release and is already implemented in the [`v0.5-dev`](https://github.com/Seeker14491/opener/tree/v0.5-dev) branch.

**Comment by kinnison** [comment] 2021-01-27 08:33
@Seeker14491 That's fantastic news.  Do you have a timeline on releasing that?

**Comment by kinnison** [comment] 2021-06-08 17:41
@Seeker14491 I appreciate we're pinging you quite a bit recently, but... any word on 0.5 ?

**Comment by Seeker14491** [comment] 2021-06-10 06:46
I'm having another go at fixing several issues people have reported in the `opener` crate, and I plan on putting out a release within a few days at most.

**Comment by kinnison** [comment] 2021-06-10 07:22
> I'm having another go at fixing several issues people have reported in the `opener` crate, and I plan on putting out a release within a few days at most.

That is fantastic news.  Please don't let me rush you though - take your time :D

**Comment by Seeker14491** [comment] 2021-06-13 10:57
This should be fixed now with the merging of https://github.com/rust-lang/rustup/pull/2792.

**Comment by kinnison** [comment] 2021-06-13 11:20
Aha thanks @Seeker14491

**Closed as completed by kinnison** 2021-06-13 11:20 UTC
Labels: bug

**Comment by sudoforge** [comment] 2021-08-21 21:36
Is there any chance that this could be added to a `1.24.4` release?

**Comment by sudoforge** [comment] 2021-08-21 21:45
What I'm really asking/saying is:

I'm impatient and would like this to be considered a hotfix, considering it is a regression.

For additonal context, it doesn't appear to use either the `BROWSER` environment variable, _or_ the default browser set with XDG. I'm going to open an issue with `opener` directly.

```
➜ echo $BROWSER
qutebrowser
                                                                                                                        

➜ xdg-settings get default-web-browser
org.qutebrowser.qutebrowser.desktop


➜ pstree 918976
rustup───sh───chromium─┬─chromium───chromium───19*[{chromium}]
                       ├─chromium───chromium─┬─chromium───5*[{chromium}]
                       │                     └─2*[chromium───12*[{chromium}]]
                       ├─chromium───7*[{chromium}]
                       └─19*[{chromium}]
```

**Comment by sudoforge** [comment] 2021-08-22 00:11
To any future readers, this was due to the `xdg-mime` configuration for `text/html` being set to `chromium.desktop`. To resolve this:

```
xdg-mime default <your preferred application> text/html
```
