### ISSUE TITLE
Installing an old toolchain (1.7.0) with rustup on macOS 10.12 hangs rustup

### ISSUE THREAD

**Issue by mystor** [rust-lang/rustup#1057] opened 2017-04-12 01:05 UTC
It appears as though rustup invokes `rustc --version` after installing. As rustc 1.7.0 does not run on macOS 10.12, the rustc invocation then hangs, and rustup fails to exit.

I imagine a good way to fix this problem would be to implement a timeout on the execution of the `rustc --version` command and report an error if it fails.

cc @brson who I was talking about this with on IRC.

stacktrace
```
  * frame #0: 0x00007fffa5ca0eb6 libsystem_kernel.dylib`__select + 10
    frame #1: 0x000000010fdebff9 rustup`std::process::Child::wait_with_output::h715f329fe7104e7f + 857
    frame #2: 0x000000010fdeb9da rustup`std::process::Command::output::h900750b876e1c478 + 234
    frame #3: 0x000000010fbcdb52 rustup`rustup_init::common::rustc_version::h212ab25f6ef20520 + 738
    frame #4: 0x000000010fbc8c89 rustup`_$LT$core..iter..Map$LT$I$C$$u20$F$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$::next::h4cd1a504d8b0158d + 297
    frame #5: 0x000000010fbccb49 rustup`rustup_init::common::show_channel_updates::h51239c01277880ba + 217
    frame #6: 0x000000010fbcc9c9 rustup`rustup_init::common::show_channel_update::h4dbf5d2e61cd19fc + 201
    frame #7: 0x000000010fbe1d97 rustup`rustup_init::rustup_mode::update::h6a6e86ac3e011029 + 5015
    frame #8: 0x000000010fbcf3ab rustup`rustup_init::rustup_mode::main::h407750f090a6dded + 1563
    frame #9: 0x000000010fbf66a1 rustup`rustup_init::run_multirust::h7701e04292061be6 + 2241
    frame #10: 0x000000010fbf5d3a rustup`rustup_init::main::h6b97e65baef24abd + 26
    frame #11: 0x000000010fdf785b rustup`__rust_maybe_catch_panic + 27
    frame #12: 0x000000010fdf6907 rustup`std::rt::lang_start::h74b3afbdd8daef1c + 391
    frame #13: 0x000000010fbc0e44 rustup`start + 52
```

command output
```
$ rustup run 1.7.0 rustc --version
rustc(2582,0x7fffaea843c0) malloc: *** malloc_zone_unregister() failed for 0x7fffaea7a000
```

**Comment by Diggsey** [comment] 2017-05-04 00:02
Dupe of #729

**Closed as completed by Diggsey** 2017-05-04 00:02 UTC
