### ISSUE TITLE
rust lang doc offline command in two different platforms

### ISSUE THREAD

**Issue by saifnoorprottoy** [rust-lang/rustup#947] opened 2017-02-10 10:01 UTC
(Hello, I am new guy in the area of Rust lang ) 
seems that the `rustup doc --book` is failing to work properly , I've tried the command in two different platforms (windows and ubuntu) and it shows the same output which is **nothing** . By using the command `rustup component add rust-docs` ( which I found on the related issue #901 by googling) it solves the problem but ...I guess the command should be able to deal with that. thanks

**Comment by brson** [comment] 2017-03-16 22:45
Thanks for the report @saifnoorprottoy !

It does look like a dupe of https://github.com/rust-lang-nursery/rustup.rs/issues/901

**Closed as completed by brson** 2017-03-16 22:45 UTC
