### ISSUE TITLE
Faulty VC++ build tools diagnostic on Windows 10

### ISSUE THREAD

**Issue by Rojetto** [rust-lang/rustup#931] opened 2017-01-23 22:35 UTC
I just tried to install Rust via rustup on Windows 10 64 bit. After running rustup-init it complained about the missing VC++ build tools (as it should, I didn't have them installed).
I then downloaded and installed them with the first link it suggested (http://landinghub.visualstudio.com/visual-cpp-build-tools). After rebooting and running rustup it still complained about them allegedly missing. I then just ignored the warning and continued with the installation, which completed succesfully. The target it defaulted to and that it installed is x86_64-pc-windows-msvc. Compiling and running a simple rust program also worked, so it seems like just the diagnostic, whether the build tools are installed didn't work.

**Comment by Ryan1729** [comment] 2017-02-23 03:01
I had a similar experience and after installing rust I was able to compile the rust-sdl2 examples (after installing the required sdl2 files) so it also works on slightly more involved programs, including those relying on libraries from other languages, despite the diagnostic reporting otherwise.

**Comment by brson** [comment] 2017-03-16 23:02
Thanks for the report @Rojetto !

This is a duplicate of https://github.com/rust-lang-nursery/rustup.rs/issues/660 and should be fixed in the next release.

**Closed as completed by brson** 2017-03-16 23:02 UTC
