### ISSUE TITLE
Please update sh.rustup.sh

### ISSUE THREAD

**Issue by jeffallen** [rust-lang/rustup#3523] opened 2023-11-05 09:47 UTC
### Problem

In commit 900d3d63ead304af4ca2c96575e81c69027a44cb, a bug making Illumos installs fail got fixed.

The update has not been deployed to sh.rustup.rs yet.

Using `curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh | sh` works now, but `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` does not because it has not been updated.

### Steps

1. `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. It doesn't work.
3. `curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh | sh`
4. It works.

### Rustup version

```console
The live one right now.
```

### Installed toolchains

```console
None, it won't work.
```

**Comment by rami3l** [comment] 2023-11-05 10:01
Hi @jeffallen, thanks for filing this issue!

We are aware of it and, as a matter of fact, are actively working towards a new release in #3501.

Once that issue is closed, the shell script on the server that you mentioned will be up to date. We are very close to done now, please stay tuned!

**Comment by rami3l** [comment] 2023-11-05 10:15
I'm closing this one as a duplicate of #3501. Please feel free to tell us if you have other concerns :)

**Closed as not planned** 2023-11-05 10:16 UTC
Labels: bug
