### ISSUE TITLE
Rustup refusing to update nightly beyond 2020-11-24 (1c389ffef) -- missing installed component rustfmt?

### ISSUE THREAD

**Issue by Vbbab** [rust-lang/rustup#2597] opened 2020-12-05 22:07 UTC
**Problem**
`rustup check` shows for `nightly`:
```
nightly-x86_64-pc-windows-msvc - Update available : 1.50.0-nightly (1c389ffef 2020-11-24) -> 1.50.0-nightly (3ff10e74a 2020-12-04)
```

However upon running `rustup update`, I get the following log for `nightly` updates:
```
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: latest update on 2020-12-05, rust version 1.50.0-nightly (3ff10e74a 2020-12-04)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-12-04-x86_64-pc-windows-msvc'
info: latest update on 2020-12-04, rust version 1.50.0-nightly (5be3f9f10 2020-12-03)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-12-03-x86_64-pc-windows-msvc'
info: latest update on 2020-12-03, rust version 1.50.0-nightly (f4db9ffb2 2020-12-02)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-12-02-x86_64-pc-windows-msvc'
info: latest update on 2020-12-02, rust version 1.50.0-nightly (6645da366 2020-12-01)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-12-01-x86_64-pc-windows-msvc'
info: latest update on 2020-12-01, rust version 1.50.0-nightly (b7ebc6b0c 2020-11-30)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-11-30-x86_64-pc-windows-msvc'
info: latest update on 2020-11-30, rust version 1.50.0-nightly (349b3b324 2020-11-29)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-11-29-x86_64-pc-windows-msvc'
info: latest update on 2020-11-29, rust version 1.50.0-nightly (e37f25aa3 2020-11-28)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-11-28-x86_64-pc-windows-msvc'
info: latest update on 2020-11-28, rust version 1.50.0-nightly (6a889570e 2020-11-27)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-11-27-x86_64-pc-windows-msvc'
info: latest update on 2020-11-27, rust version 1.50.0-nightly (72da5a9d8 2020-11-26)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-11-26-x86_64-pc-windows-msvc'
info: latest update on 2020-11-26, rust version 1.50.0-nightly (b48cafd9e 2020-11-25)
info: skipping nightly which is missing installed component 'rustfmt'
info: syncing channel updates for 'nightly-2020-11-25-x86_64-pc-windows-msvc'
info: checking for self-updates
```

`rustup` is refusing to update because updates are `missing installed component 'rustfmt'`?

**Steps**

1. `rustup check` -- Update available for `nightly-x86_64-pc-windows-msvc`
2. `rustup update` when `rustup default nightly` -- **FAILED**

Why is `rustup` complaining about missing `rustfmt`? Is it just that the `nightly` releases are still too early?

**Notes**

Output of `rustup --version`: 
```
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.48.0 (7eac88abb 2020-11-16)`
```

Output of `rustup show`:
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\User\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.48.0 (7eac88abb 2020-11-16)
```

**Comment by ehuss** [comment] 2020-12-05 23:11
Components are allowed to go into a "broken" state on nightly.  There is some documentation about this here: https://rust-lang.github.io/rustup/concepts/components.html#component-availability and https://rust-lang.github.io/rustup/concepts/channels.html#nightly-availability

You can use `--profile=minimal` or `--force` to force install a nightly release with a missing component.

**Comment by kinnison** [comment] 2020-12-08 09:34
@Vbbab Do you need any further assistance or can I close this issue?  it's definitely not a bug in rustup.

**Comment by Vbbab** [comment] 2020-12-11 05:15
OK, thanks for the clarifications! I have no more questions.

**Closed as completed** 2020-12-11 05:16 UTC
Labels: question, not-rustup
