### ISSUE TITLE
After install aarch64-linux-android still show  not install 

### ISSUE THREAD

**Issue by HuixingWong** [rust-lang/rustup#3426] opened 2023-08-04 02:54 UTC
### Problem

note: the `aarch64-linux-android` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-linux-android`

### Steps

 rustup target add aarch64-linux-android

info: component 'rust-std' for target 'aarch64-linux-android' is up to date

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.69.0 (84c898d65 2023-04-16)`
```

### Installed toolchains

```console
installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-apple-ios
aarch64-apple-ios-sim
aarch64-linux-android
aarch64-unknown-none
armv7-linux-androideabi
i686-linux-android
x86_64-apple-ios
x86_64-linux-android

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.69.0 (84c898d65 2023-04-16)
```

**Comment by rami3l** [comment] 2023-08-18 12:17
@HuixingWong Hi!

Would you mind sharing the command that you executed causing that error message? I see you have `aarch64-linux-android` in your list of installed targets.

There could be a problem of wrong error message being generated...

---

Update: That suggestion is indeed possibly wrong (but it is not generated by `rustup` anyway so we cannot do anything about it on our side, sorry).

My guess would be that you are actually using a different toolchain in `cargo`, but is prompted by `rustc` to add the target on the default toolchain.

cc https://github.com/rust-lang/rust/issues/91600

**Comment by rami3l** [comment] 2023-08-18 12:44
@weihanglo:

> If you have multiple installations of `rust` on your machine, please make sure that you are using the `rustup`-installed one.
> 
> See: https://users.rust-lang.org/t/compile-failed-with-target-aarch64-linux-android/92439/14

---

My personal recommendation for setting up a `rust` environment on macOS would be:
1. Install `rustup-init` with `brew install rustup-init`;
2. Proceed with that `rustup-init` installation;
3. If you also wish to have `brew`-installed `rust`, make sure your `rustup`-installed `rust` comes first in the `PATH`, and optionally [configure the system toolchain](https://rust-lang.github.io/rustup/installation/package-managers.html) via `rustup toolchain link system <path>`.

**Comment by paul726** [comment] 2023-12-09 16:28
@rami3l thank you so much, this way works for me

**Comment by rami3l** [comment] 2023-12-20 11:39
Since the info given in this issue is not enough to reproduce it, I'm closing this issue now.

Please feel free to tell me if there's anything we can do for you, and have a good day!

**Closed as not planned by rami3l** 2023-12-20 11:39 UTC
Labels: bug
