### ISSUE TITLE
Update fails: directory does not exist: 'bin/cargo-clippy.exe'

### ISSUE THREAD

**Issue by Luc108** [rust-lang/rustup#2800] opened 2021-06-19 14:10 UTC
**Problem**

Updating rust fails

**Steps**

1.  rustup update

**Notes**

Output of rustup update (most relevant parts):

error: failure removing component 'clippy-preview-x86_64-pc-windows-msvc', directory does not exist: 'bin/cargo-clippy.exe'

stable-x86_64-pc-windows-msvc update failed - rustc 1.51.0 (2fd73fabe 2021-03-23)

rustup 1.24.3 (ce5817a94 2021-05-31)

Output of `rustup show`:

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\lucbr\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)

**Comment by rbtcollins** [comment] 2021-06-20 22:17
duplicate of #1480 I think, though its odd that #2799 was also failed with the same exact symptom; I wonder if some exterior agent has caused this

**Closed as completed by rbtcollins** 2021-06-20 22:17 UTC
Labels: bug
