### ISSUE TITLE
Unable to install rustup on WSL

### ISSUE THREAD

**Issue by VictorAlbertsson** [rust-lang/rustup#2277] opened 2020-04-02 19:44 UTC
I've been looking around the internet for some time now and haven't found a solution to my problem. I'm running Arch Linux under WSL version 1  and am unable to install rustup.

When running `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` it fails, outputting: 

> info: installing component 'cargo'
   4.9 MiB /   4.9 MiB (100 %)   1.7 MiB/s in  1s ETA:  0s
   thread 'main' panicked at 'assertion failed: `(left == right)`
   left: `22`,
   right: `4`', src/libstd/sys/unix/thread.rs:172:21
   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

After executing `export RUST_BACKTRACE=1` I get the following additional output:

> stack backtrace:
   0: \<unknown>
   1: \<unknown>
   2: \<unknown>
   3: \<unknown>
   4: \<unknown>
   5: \<unknown>
   6: \<unknown>
   7: \<unknown>
   8: \<unknown>
   9: \<unknown>
  10: \<unknown>
  11: \<unknown>
  12: \<unknown>
  13: \<unknown>
  14: \<unknown>
  15: \<unknown>
  16: \<unknown>
  17: \<unknown>
  18: \<unknown>
  19: __libc_start_main
  20: \<unknown>
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Furthermore after running `export RUST_BACKTRACE=full` I get:
> stack backtrace:
   0:     0x7f97bb95f12c - \<unknown>
   1:     0x7f97bb637c7c - \<unknown>
   2:     0x7f97bb95e7e6 - \<unknown>
   3:     0x7f97bb95e39e - \<unknown>
   4:     0x7f97bb95db43 - \<unknown>
   5:     0x7f97bb95d6be - \<unknown>
   6:     0x7f97bb95d650 - \<unknown>
   7:     0x7f97bb92dd36 - \<unknown>
   8:     0x7f97bb91fc1f - \<unknown>
   9:     0x7f97bb8fbe47 - \<unknown>
  10:     0x7f97bb8ea6f8 - \<unknown>
  11:     0x7f97bb8cf474 - \<unknown>
  12:     0x7f97bb8cca81 - \<unknown>
  13:     0x7f97bb58b70a - \<unknown>
  14:     0x7f97bb563a5f - \<unknown>
  15:     0x7f97bb5a2037 - \<unknown>
  16:     0x7f97bb5a12a3 - \<unknown>
  17:     0x7f97bb547153 - \<unknown>
  18:     0x7f97bb5aa968 - \<unknown>
  19:     0x7f97bae57023 - __libc_start_main
  20:     0x7f97bb54610e - \<unknown>
  21:                0x0 - \<unknown>

So initially I thought the problem was with cargo but when I compiled cargo from source it went fine. Installing rust from the official repositories works as well. Any help would be greatly appreciated!

**Comment by rbtcollins** [comment] 2020-04-02 19:56
Duplicate of #2245

**Closed as completed by rbtcollins** 2020-04-02 19:56 UTC
Labels: bug
