### ISSUE TITLE
when download is resumed, bandwith numbers are exaggerated 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustup#2255] opened 2020-03-08 00:52 UTC
When I cancel a "rustup update" and resume it later, rustup thinks it downloaded everything that was previously downloaded *right this second* and reports incredible high bandwidth:
`126.7 MiB / 201.2 MiB ( 63 %)  62.5 MiB/s in  3s ETA:  1s`
or
`201.2 MiB / 201.2 MiB (100 %) 166.5 MiB/s in  1s ETA:  0s`

**Steps**

1. rustup update
2. ctrl+c
3. rustup update

**Possible Solution(s)**
Start the some internal "already-downloaded" value at 0 and use it to calculate accurate download bandwidth when a downloaded is resumed.

**Notes**

Output of `rustup --version`: `rustup 1.21.1 (7832b2ebe 2019-12-20)`

**Comment by rbtcollins** [comment] 2020-03-08 01:35
It is true that this happens. Fixing it will require recording metadata about the time it took to do the partial download, or teaching the reporting system to be able to report on full progress but calculate bandwidth on only part of the progress. Or something like that.

**Comment by kinnison** [comment] 2020-03-08 09:52
Yes, I figure that given the message about resuming is distinct, we might be able to have a constructor for the download monitor which copes with this topic.

**Comment by abcarroll** [comment] 2020-07-06 01:42
I'm new here, apologies if I'm out of line stating this.

This is a duplicate of #1166, it looks like.

**Comment by rami3l** [comment] 2024-12-31 01:43
Thanks @abcarroll for the triage!

**Closed as duplicate by rami3l** 2024-12-31 01:43 UTC
Labels: bug, help wanted
