### ISSUE TITLE
Please use FreeDesktop $HOME/.config/ directory recommendation for *nix systems

### ISSUE THREAD

**Issue by aplatypus** [rust-lang/rustup#3498] opened 2023-10-04 15:30 UTC
### Problem you are trying to solve

The `rustup` install shell script announces that it will load and create two related directories:

* `~/.rustup`
* `~/.cargo`

This adds to the burden of config data and metadata in _dot-directories_ and _dot-files_ on *nix systems.  My personal practice is to place all _dot-_ files and directories under the recommended `~/.config/` directory; even when I am forced to create symbolic a link, as in this example: "`.mysql --> .config/mysql`".

In the same section of `rustup` ... the script informs me that these locations can be modified respectively with:

* `RUSTUP_HOME` and
* `CARGO_HOME`

 environment variables.  At that point I cancelled the `rustup` shell install script and defined the relevant environment variables and re-ran the script with encouraging results.  The initial preamble reported that the installer would use the: 

* `~/.config/rustup/`
* `~/.config/.cargo/`

... directories defined by the respective environment variables.  The installer did an excellent job "_enabling_" the specified directories.  Well done rustup team :-D

### Solution you'd like

I would prefer that the default configuration and metadata follow the OpenDesktop standard and place settings and data under the `$HOME/.config/` directory.

The `rustup` script could use the environment variables [FreeDesktop](https://www.freedesktop.org/software/systemd/man/environment.d.html) specification for setting environment variables.

* https://www.freedesktop.org/software/systemd/man/environment.d.html

Furthermore, this allows users to keep configuration information under one umbrella directory and improve general admin and maintenance processing.  

### Notes

Please see:

*   #3123 and
*  #2883

... for a more rounded view of this opportunity.

* I appreciate that there  are _challenges_  raised for non-`systemd`_ installations.
  * However, some common, reasonable and pragmatic approach would probably enhance the configuration and maintenance process in any case.
* Personally speaking, I'd like to _tame_ all "`.-files`" and have them under a common location like `~/.config/...`

**Comment by rami3l** [comment] 2023-10-04 16:01
@aplatypus Thanks for filing this issue!

It so happened that we have just discussed about making PATH changes persistent in https://github.com/rust-lang/rustup/issues/3495#issuecomment-1742552658.

Although I'm personally okay with such a change, unfortunately the consensus was that it was out of scope and will not be implemented.

(cc @rbtcollins for closing some relevant issues)

**Comment by djc** [comment] 2024-09-11 10:13
Going to close this as a duplicate of https://github.com/rust-lang/rustup/issues/247.

**Closed as not planned by djc** 2024-09-11 10:13 UTC
Labels: enhancement
