### ISSUE TITLE
"error reading rustc version" installing windows-gnu

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#1151] opened 2017-06-06 16:22 UTC
I'm not sure what causes this, but the toolchain does seem to work.

```
$ RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org rustup update stable-i686-pc-windows-gnu
info: syncing channel updates for 'stable-i686-pc-windows-gnu'
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: downloading component 'rust-mingw'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: installing component 'rust-mingw'

  stable-i686-pc-windows-gnu installed - (error reading rustc version)
```

**Comment by mati865** [comment] 2017-06-11 09:02
Does it still happen after https://github.com/rust-lang-nursery/rustup.rs/pull/1130?

**Comment by mati865** [comment] 2017-06-19 14:54
I was able to reproduce this issue on 14 years old HDD with both Windows and Linux:
```
$ rustup update
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates

  nightly-x86_64-unknown-linux-gnu unchanged - (timeout reading rustc version)
```
But I doubt somebody is still using such old HDD for main partition.

@brson ping. Do you still have this issue after updating to rustup 1.4.0?

**Comment by Diggsey** [comment] 2017-06-25 11:13
Looks like a dupe of #1118

**Closed as completed by Diggsey** 2017-06-25 11:13 UTC
Labels: bug
