### ISSUE TITLE
Unable to update - thread 'main' panicked at 'assertion failed: `(left == right)` - when installing cargo

### ISSUE THREAD

**Issue by iCodeSometime** [rust-lang/rustup#2253] opened 2020-03-05 17:43 UTC
**Problem**
When I run `rustup update`, I receive an error directly after "info: installing component cargo"
The full error is:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:167:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:167:21
stack backtrace:
   0:     0x7ff664296138 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x7ff664296138 - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x7ff664296138 - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x7ff664296138 - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x7ff664296138 - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x7ff664295887 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x7ff664295887 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x7ff6642953af - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x7ff66429535c - std::panicking::begin_panic_fmt::hc33ce01c7f7cd52d
                               at src/libstd/panicking.rs:339
   9:     0x7ff66402820e - <rustup::diskio::threaded::Threaded as rustup::diskio::Executor>::join::h2e1801c8c3678ad9
  10:     0x7ff6640279a6 - core::ptr::real_drop_in_place::h2ddd51c205d71ba0
  11:     0x7ff66429ed50 - core::ptr::real_drop_in_place::h0001e80730c8961a
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ptr/mod.rs:175
  12:     0x7ff66401c01d - rustup::dist::component::package::unpack_without_first_dir::hebaa71a922aea521
  13:     0x7ff663ffc0fc - rustup::dist::manifestation::Manifestation::update::ha584df3fa09d6def
  14:     0x7ff663feb461 - rustup::dist::dist::try_update_from_dist_::hcadc159ed8563555
  15:     0x7ff663fd251e - rustup::toolchain::Toolchain::install::h9fd2721981117c52
  16:     0x7ff663fcfd9f - rustup::toolchain::Toolchain::install_from_dist::hb30f89cf2e809056
  17:     0x7ff663f00d1e - rustup_init::rustup_mode::update::h6ab51c748eaeb292
  18:     0x7ff663ed6b39 - rustup_init::rustup_mode::main::h6d7ce19928d9f88a
  19:     0x7ff663f1c347 - rustup_init::run_rustup_inner::hc570d3222a327e8f
  20:     0x7ff663f1b7f5 - rustup_init::main::hc72017b61fdb958c
  21:     0x7ff663eb62f3 - std::rt::lang_start::{{closure}}::h1f7d8a651250686e
  22:     0x7ff663f2083e - main
  23:     0x7ff663ad5023 - __libc_start_main
  24:     0x7ff663eb2029 - <unknown>
thread panicked while panicking. aborting.
[2]    730 illegal hardware instruction (core dumped)  rustup update
```

**Steps**

1. run `rustup update`

**Notes**

Output of `rustup --version`:
```rustup 1.20.2 (13979c968 2019-10-16)```
Output of `rustup show`:
```Default host: x86_64-unknown-linux-gnu
rustup home:  /home/kcochran/.rustup

stable-x86_64-unknown-linux-gnu (default)
(rustc does not exist)```

I am using Arch running in WSL

**Comment by iCodeSometime** [comment] 2020-03-05 17:49
I get the same error when installing rustup after uninstalling.
Though, it had been working fine previously

**Comment by lunik1** [comment] 2020-03-07 21:47
I get the same issue using Arch on WSL when installing `rust-src`. `rustup` version is `1.21.1 (2020-02-23)`. Full error:
```
info: installing component 'rust-src'
  2.3 MiB /   2.3 MiB (100 %) 401.6 KiB/s in  6s ETA:  0s
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:172:21
stack backtrace:
   0:     0x7f1f5c29412c - <unknown>
   1:     0x7f1f5bf6cc7c - <unknown>
   2:     0x7f1f5c2937e6 - <unknown>
   3:     0x7f1f5c29339e - <unknown>
   4:     0x7f1f5c292b43 - <unknown>
   5:     0x7f1f5c2926be - <unknown>
   6:     0x7f1f5c292650 - <unknown>
   7:     0x7f1f5c262d36 - <unknown>
   8:     0x7f1f5c254c1f - <unknown>
   9:     0x7f1f5c230e47 - <unknown>
  10:     0x7f1f5c21f6f8 - <unknown>
  11:     0x7f1f5c204474 - <unknown>
  12:     0x7f1f5c201a81 - <unknown>
  13:     0x7f1f5bec1bd1 - <unknown>
  14:     0x7f1f5be96c93 - <unknown>
  15:     0x7f1f5bed7037 - <unknown>
  16:     0x7f1f5bed62a3 - <unknown>
  17:     0x7f1f5be7c153 - <unknown>
  18:     0x7f1f5bedf968 - <unknown>
  19:     0x7f1f5b787023 - __libc_start_main
  20:     0x7f1f5be7b10e - <unknown>
  21:                0x0 - <unknown>
info: rolling back changes
```

**Comment by lunik1** [comment] 2020-03-07 22:38
Using `rustup` not from the repost does not help, but you do get a more detailed backtrace:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
stack backtrace:
   0:     0x7fdf5acdbc9c - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x7fdf5acdbc9c - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x7fdf5acdbc9c - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7fdf5acdbc9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7fdf5a9ba81c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7fdf5acdb526 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x7fdf5acdb19e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7fdf5acdb19e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7fdf5acdb19e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x7fdf5acda943 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x7fdf5acda943 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x7fdf5acda4be - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x7fdf5acda450 - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x7fdf5acaae86 - <rustup::diskio::threaded::Threaded as rustup::diskio::Executor>::join::hf33124263a81d2a4
  14:     0x7fdf5ac9cd40 - rustup::dist::component::package::unpack_without_first_dir::h352b57d236248e9a
  15:     0x7fdf5ac762f6 - rustup::dist::manifestation::Manifestation::update::h8c800deec8167b5b
  16:     0x7fdf5ac64b8a - rustup::dist::dist::try_update_from_dist_::h113375517e7a85ca
  17:     0x7fdf5ac4964c - rustup::toolchain::Toolchain::install::h048b51ffab245b48
  18:     0x7fdf5ac46c8c - rustup::toolchain::Toolchain::install_from_dist::h00b9aafeb93470e5
  19:     0x7fdf5a905f1f - rustup_init::rustup_mode::update::hbe56e74e72e7ae31
  20:     0x7fdf5a8dc2ca - rustup_init::rustup_mode::main::h2c97a39c05d9bf7c
  21:     0x7fdf5a923b1c - rustup_init::run_rustup_inner::ha545371fd2dc19a6
  22:     0x7fdf5a922d64 - rustup_init::main::hba9a23e308c96901
  23:     0x7fdf5a8b7a03 - std::rt::lang_start::{{closure}}::h1778d9ce6385bef5
  24:     0x7fdf5a92c458 - main
  25:     0x7fdf5a475023 - __libc_start_main
  26:     0x7fdf5a8b4029 - <unknown>
info: rolling back changes
```

**Comment by rbtcollins** [comment] 2020-03-07 23:35
Duplicate of #2245

**Closed as completed by rbtcollins** 2020-03-07 23:35 UTC
Labels: bug
