### ISSUE TITLE
Fix rustup installer

### ISSUE THREAD

**Issue by eykamp** [rust-lang/rustup#3471] opened 2023-09-03 02:21 UTC
In installed rust on a clean Raspberry Pi 4 with the current version or raspberian using `curl https://sh.rustup.rs -sSf | sh`, which I understand is the supported method for installing rust.  It failed. 

The solution was to use a non-default option, as described here:
https://stackoverflow.com/questions/67148415/fail-to-run-cargo-after-install-rust-on-raspberry-pi-4

I think it would be great if the install script could detect a Raspberry Pi and provide the correct default option.

I had the exact same set of issues described here:  https://github.com/rust-lang/rustup/issues/2565

**Comment by rami3l** [comment] 2023-09-03 02:55
@eykamp Thanks for your report!

## Triage Report

### Related issues

#2565 #3431 #3307 #3342 #3420 #3487

### Possible cause

https://forums.raspberrypi.com/viewtopic.php?t=289963#p1756063 says:
> although the Pi was running a **32 bit user land** the kernel identified as 64 bit, which confused the Rust installer.

https://github.com/rust-lang/rustup/issues/2565#issuecomment-733283796 says:
> The output of `ldd rustc` suggests you don't - and in fact despite having an aarch64 CPU you're running an `armhf` userland which is something we weren't expecting.

So I suspect that `rustup` wants to install `aarch64-unknown-linux-gnu` (or similar) because it has detected a 64-bit Linux (which is correct).
However, your PiOS user land is 32-bit, so only something like `arm-unknown-linux-gnueabihf` will work.

### Possible solution

We could choose to do one (or many) of the following:

* Add new doc pages and/or heredoc strings to explain this.
* Automatically detect the multi-arch case. That is, make a new patch similar to #3438. However, this might not be easily tested by the CI.
  - In this case, @MichaIng's comment in https://github.com/rust-lang/rustup/issues/3307#issuecomment-1515293363 might be very useful.
* Add a verifying step (e.g. `rustc --version`) at the end of the installation, like what `homebrew` does. If it fails, print diagnostics (for issue filing) and simple suggestions.

**Comment by rami3l** [comment] 2023-09-03 03:15
@rbtcollins Should we rely on something like `cc -dumpmachine` instead to be more user land-aware?

**Comment by rami3l** [comment] 2023-10-05 09:04
Duplicate of #3307.

**Closed as not planned** 2023-10-05 09:17 UTC
