### ISSUE TITLE
Rustup concurrent Install removes rustc

### ISSUE THREAD

**Issue by onerandomusername** [rust-lang/rustup#2806] opened 2021-06-24 18:22 UTC
**Problem**

Running concurrent installers or updates can cause both of them to error and remove rust from the system. Expected behavior should not allow the second installer to start if there is already one installer. 
![image](https://user-images.githubusercontent.com/71233171/123313031-0de42c00-d4f7-11eb-9b2e-3f6d969a4d50.png)

**Steps**

1. Run `rustup install <stable|beta|nightly>` or, if there's a pending update, `rustup update`
2. Repeat step 1 in a new terminal, so rustup is updating or installing twice 

**Possible Solution(s)**

Add a lock to the installer to ensure that rustup will be updating or installing (or uninstalling) on only one terminal window at a time.
**Notes**

Output of `rustup --version`: `rustc 1.53.0 (53cb7b09b 2021-06-17)`
Output of `rustup show:
rustup home:  C:\Users\aru\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
beta-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.53.0 (53cb7b09b 2021-06-17)

**Comment by kinnison** [comment] 2021-06-25 08:34
Locking `$RUSTUP_HOME` is something we've talked about before.  I'm not sure, but there is likely to be similar bugs which might be markable as related to this, or even a bunch of dups.

**Comment by rbtcollins** [comment] 2021-06-27 20:36
duplicate of #988 (which is a pinned bug :))

**Closed as completed by rbtcollins** 2021-06-27 20:36 UTC
Labels: bug

**Comment by onerandomusername** [comment] 2021-06-27 22:35
> 
> 
> duplicate of #988 (which is a pinned bug :))

Ahhh, sorry, can't believe I missed that!
