### ISSUE TITLE
install script error info: downloading installer sh: line 570:  1607 Segmentation fault: 11  "$@" 

### ISSUE THREAD

**Issue by AuroraPetard** [rust-lang/rustup#3744] opened 2024-03-28 03:57 UTC
### Problem

when i try use rustup update rust but not work so i reinstall  use  rustup self uninstall 
and then reinstall rustup use offical script 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
but when i execute this script occur this error i cant fix it please help me 
info: downloading installer
sh: line 570:  1607 Segmentation fault: 11  "$@"

### Steps

rustup update 
rustup self uninstall 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

### Possible Solution(s)

so i try use offline install way pkg package but not have rustup 
macos 10.15.2 catalina 

### Rustup version

```console
no
```

### Installed toolchains

```console
no
```

**Comment by rami3l** [comment] 2024-03-28 05:27
I'm closing this issue as a duplicate of #3708. For the moment being, please use the quick fix in https://github.com/rust-lang/rustup/issues/3708#issuecomment-1993590209.

**Closed as not planned** 2024-03-28 05:28 UTC
Labels: bug
