### ISSUE TITLE
Toolchain uninstall not discoverable (asymmetry in argument handling)

### ISSUE THREAD

**Issue by ideasman42** [rust-lang/rustup#957] opened 2017-02-19 02:16 UTC
The documentation shows how to install nightly: https://github.com/rust-lang-nursery/rustup.rs#working-with-nightly-rust

    rustup install nightly

However the reverse doesn't work:

    rustup uninstall nightly

I asked for help on IRC and was told that `rustup toolchain install nightly` / `rustup toolchain uninstall nightly` work. Which is good, but not very discoverable.

Suggest that either:

- `rustup uninstall nightly` be supported.
- `rustup toolchain install nightly` be the documented way to install nightly.

Or at the very least, document that `rustup toolchain uninstall nightly` is the reverse of `rustup install nightly`.

**Comment by brson** [comment] 2017-03-16 22:40
Yeah, you're right the interface here is confusing. Not sure offhand what I want to do. There's a fair bit about the UI a no longer am happy with.

**Comment by Diggsey** [comment] 2017-05-04 00:01
Dupe of #730

**Closed as completed by Diggsey** 2017-05-04 00:01 UTC
