### ISSUE TITLE
Toolchain file not properly resolving Rust 1.79

### ISSUE THREAD

**Issue by Rigidity** [rust-lang/rustup#3953] opened 2024-07-16 23:01 UTC
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

I have the following `rust-toolchain.toml` file in my project:

```rs
[toolchain]
channel = "1.79"
components = ["rustfmt", "clippy"]
```

And when I run any `cargo` command, it fails with:
```
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.79-aarch64-apple-darwin' toolchain
```

Changing the `rust-toolchain.toml` to either of these resolves the issue (though is not what I want):

```rs
[toolchain]
channel = "1.78"
components = ["rustfmt", "clippy"]
```

```rs
[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]
```

### Steps

1. Create a new Rust project with `cargo init`
2. Create a `rust-toolchain.toml` file and add `channel = "1.79"` to the `[toolchain]` section
3. Run a `cargo` command (even with 1.79 installed, this fails)

### Notes

I have attempted to do all of the following before filing this bug:
* Update Rustup
* Reinstall Rustup
* Update my toolchain
* Reinstall both `stable` and `1.79`
* Reinstall the `cargo` and `clippy` components manually
* Delete the `~/.rustup` directory
* Delete the `~/.cargo` directory
* Ensured that the toolchain does in fact contain the required components
* Ensured that the installed version of Cargo is in fact 1.79

### Rustup version

```console
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.79.0 (129f3b996 2024-06-10)`
```

### Installed toolchains

```console
Default host: aarch64-apple-darwin
rustup home:  /Users/rigidity/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
1.79.0-aarch64-apple-darwin (default)
1.78-aarch64-apple-darwin
1.79-aarch64-apple-darwin

active toolchain
----------------

stable-aarch64-apple-darwin (overridden by '/Users/rigidity/Desktop/chia-rs/rust-toolchain.toml')
rustc 1.79.0 (129f3b996 2024-06-10)
```

### OS version

```console
MacOS 14.5
```

**Comment by Rigidity** [comment] 2024-07-16 23:40
I've cloned Rustup and added some debug logging and discovered that apparently I have two toolchain folders:
* `1.79.0-aarch64-apple-darwin`
* `1.79-aarch64-apple-darwin`

The former has `cargo` and the latter doesn't. But both have some somponents.

When I use `1.78`, it resolves to the `1.78-aarch64-apple-darwin` folder, but there is no duplication with this version, so it finds `cargo` fine.

**Comment by Rigidity** [comment] 2024-07-16 23:41
So changing it to `channel = "1.79.0"` works, but `channel = "1.79"` finds the wrong directory.

**Comment by Rigidity** [comment] 2024-07-16 23:45
This is reproducible by running `rustup toolchain install 1.79` instead of `rustup toolchain install 1.79.0`
To me at least, these should resolve to the same thing until `1.79.1` is released? Not sure what the best path forward is here.

**Comment by rami3l** [comment] 2024-07-16 23:59
Duplicate of #3104.

**Closed as not planned by rami3l** 2024-07-16 23:59 UTC
Labels: bug
