### ISSUE TITLE
Change default configuration path to windows standard %APPDATA% or else

### ISSUE THREAD

**Issue by hugo-sama** [rust-lang/rustup#4017] opened 2024-09-11 09:59 UTC
### Problem you are trying to solve

Rust putting configuration and settings under user home directory.
Its inappropriate keep using path the Linux Legacy way. 
Even developers for Linux start using `XDG_CONFIG_HOME` that points to `$HOME/.config/` avoid putting everything under user home dir.

### Solution you'd like

move configuration path from `%USERPROFILE%/.rustup` to somewhere like `%APPDATA%/rustup`

[env var from microsoft](https://learn.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables#variables-that-are-recognized-only-in-the-user-context)

**Comment by djc** [comment] 2024-09-11 10:13
Going to close this as a duplicate of #247.

**Closed as not planned by djc** 2024-09-11 10:13 UTC
Labels: enhancement
