### ISSUE TITLE
Updating to a version with an invalid semver number yields a useless error message

### ISSUE THREAD

**Issue by jdm** [rust-lang/rustup#1133] opened 2017-05-24 15:26 UTC
```
$ rustup update 1.17
error: toolchain '1.17' is not installed
$ rustup --version
rustup 1.3.0 (124170c 2017-05-09)
```
I was informed that I wanted 1.17.0 instead, which worked fine.

**Comment by Diggsey** [comment] 2017-05-24 15:29
Dupe of #301

**Closed as completed by Diggsey** 2017-05-24 15:29 UTC
