### ISSUE TITLE
Display an error if the binary being run doesn't exist in the given toolchain

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#922] opened 2017-01-13 22:14 UTC
Right now rustup will attempt to e.g. run `rustdoc` blindly in a given toolchain, even if rustdoc doesn't exist (which is possible in e.g. custom toolchains). When this happens rustup will accidentally execute itself infinitely. It could instead check whether the tool actually exists before running it.

**Comment by Diggsey** [comment] 2017-01-13 23:13
@brson @Manishearth has #917 open to fix this, but the regression test is broken on CI due to there being a global rust installation in the CI environment - might need to hack PATH for the tests - what do you think?

**Comment by Diggsey** [comment] 2017-05-03 22:01
This should have been fixed with the last release.

**Closed as completed by Diggsey** 2017-05-03 22:01 UTC
