### ISSUE TITLE
rustup can`t start cargo on windows when path not match

### ISSUE THREAD

**Issue by VitalyVint** [rust-lang/rustup#952] opened 2017-02-11 12:24 UTC
start cmd.exe and than C:\users\username\.cargo\bin\cargo.EXE and `cargo` will print
error: command failed: 'cargo.EXE'
info: caused by: Не удается найти указанный файл. (os error 2)

Не удается найти указанный файл - Can`t find file.
OS - windows7 x64.

true filename is a C:\users\username\.cargo\bin\cargo.exe.

rustup 1.0.0 (17b6d21 2016-12-15)

**Comment by rubdos** [comment] 2017-03-07 18:11
I catched this on AppVeyor, where calling `cargo` in a very specific way (through a Python script, in a VS shell), tries to call cargo.EXE instead of cargo.exe:

       stack backtrace:
          0:   0x541796 - <no info>
          1:   0x437c31 - <no info>
          2:   0x43658d - <no info>
          3:   0x439afc - <no info>
          4:   0x4013de - <no info>
          5: 0x765f7c04 - BaseThreadInitThunk
          6: 0x7775ab8f - RtlInitializeExceptionChain
       error: command failed: 'cargo.EXE'
       info: caused by: The system cannot find the file specified. (os error 2)
       info: backtrace:

In English this time. `stdout` and `stderr` are probably mangled.

**Comment by rubdos** [comment] 2017-03-07 18:12
Possible duplicate of https://github.com/rust-lang-nursery/rustup.rs/issues/886 ?

**Comment by VitalyVint** [comment] 2017-03-08 09:03
yes, duplicate. It is will be ok, if i close this? Thank you for reference.

**Comment by rubdos** [comment] 2017-03-10 21:14
Yes, I think so.

**Closed as completed** 2017-03-10 21:24 UTC
