### ISSUE TITLE
target 'csky-unknown-linux-gnuabiv2hf' not found in channel

### ISSUE THREAD

**Issue by CrotchBurnt** [rust-lang/rustup#3616] opened 2024-01-02 03:29 UTC
### Problem

While installing:
> ...
> You can uninstall at any time with rustup self uninstall and
> these changes will be reverted.
> 
> Current installation options:
> 
> 
>    default host triple: x86_64-unknown-linux-gnu
>      default toolchain: stable (default)
>                profile: default
>   modify PATH variable: yes
> 
> 1) Proceed with installation (default)
> 2) Customize installation
> 3) Cancel installation
> >
> 
> info: profile set to 'default'
> info: default host triple is x86_64-unknown-linux-gnu
> info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
> error: server sent a broken manifest: missing package for component rust-std: target 'csky-unknown-linux-gnuabiv2hf' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
> 

My OS version: Fedora Linux 39 (Workstation Edition) Linux 6.6.8-200.fc39.x86_64

### Steps

1. `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/xxxx/.rustup

no active toolchain
```

**Comment by rami3l** [comment] 2024-01-02 05:31
Thanks for filing this issue!

Unfortunately, as explained in the link in the error message, the target you're referring to is a tier 3 one, so no officially prebuilt components are provided for it: `rustup` is working as expected in this case.

If you intend to build Rust code for this target and would like to install the relevant components manually, you might be able to find some useful information at https://doc.rust-lang.org/beta/rustc/platform-support/mipsel-sony-psx.html. You might need to adapt the instructions based on your target accordingly.

I'm sorry for the inconveniences, wish you have a nice day!

**Comment by CrotchBurnt** [comment] 2024-01-04 00:05
It's strange because my CPU is an AMD x86_64 one, not some C-SKY. 

Fedora Linux 6.6.8-200.fc39.x86_64

**Comment by rami3l** [comment] 2024-01-04 00:45
@CrotchBurnt Did you encounter this problem with a fresh rust installation?

If so, I suspect this to be an upstream issue similar to https://github.com/rust-lang/rustup/issues/963. I'll definitely look into it when I have time.

Reopening this issue for tracking purposes.

**Comment by CrotchBurnt** [comment] 2024-01-04 00:58
> @CrotchBurnt Did you encounter this problem with a fresh rust installation?
> 
> If so, I suspect this to be an upstream issue similar to #963. I'll definitely look into it when I have time.
> 
> Reopening this issue for tracking purposes.

Yes, it's a fresh installation. I tried on my  OpenSUSE with the same CPU architecture, same error showed.

**Comment by xen0n** [comment] 2024-01-04 09:40
I have just encountered a similar error while installing rustup on a `riscv64gc-unknown-linux-gnu` device.

```
...
info: profile set to 'default'
info: setting default host triple to riscv64gc-unknown-linux-gnu
info: syncing channel updates for 'nightly-riscv64gc-unknown-linux-gnu'
error: server sent a broken manifest: missing package for component rust-std: target 'arm64e-apple-darwin' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
```

It definitely seems the upstream manifest is broken somehow.

**Comment by rami3l** [comment] 2024-01-04 13:06
The origin of the error message seems to be the following:
https://github.com/rust-lang/rustup/blob/fe7b117b3a745e30b90ef3b6b6bbd8181162a81e/src/dist/manifest.rs#L314-L316

https://github.com/rust-lang/rustup/blob/fe7b117b3a745e30b90ef3b6b6bbd8181162a81e/src/dist/manifest.rs#L321-L334

**Comment by rami3l** [comment] 2024-01-04 13:41
@CrotchBurnt @xen0n Is the problem always about `rust-std`?

I wonder why our CI hasn't caught it...

**Comment by xen0n** [comment] 2024-01-04 13:58
> @CrotchBurnt @xen0n Is the problem always about `rust-std`?
> 
> I wonder why our CI hasn't caught it...
> 

Yeah, for now it seems to be the case.

**Comment by rami3l** [comment] 2024-01-17 06:14
@CrotchBurnt @xen0n How often are you encountering this issue? I can't seem to be able to reproduce it on my ARM64 Mac with either an ARM64 image or an x64 image:

```console
$ docker run --arch=amd64 --rm -it fedora
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:latest...
Getting image source signatures
Copying blob sha256:718a00fe32127ad01ddab9fc4b7c968ab2679c92c6385ac6865ae6e2523275e4
Copying config sha256:368a084ba17dcba88f5b23acfa47481131010219524fd9c41af87d709a04845b
Writing manifest to image destination
# uname -a
Linux ae0cb3f14644 6.6.8-200.fc39.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Dec 21 04:21:07 UTC 2023 x86_64 GNU/Linux
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
...
Current installation options:


   default host triple: x86_64-unknown-linux-gnu
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>

info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2023-12-28, rust version 1.75.0 (82e1608df 2023-12-21)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 14.3 MiB /  14.3 MiB (100 %)   9.9 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 23.6 MiB /  23.6 MiB (100 %)   9.1 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 61.4 MiB /  61.4 MiB (100 %)   8.4 MiB/s in  7s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
  7.5 MiB /   7.5 MiB (100 %)   6.4 MiB/s in  1s ETA:  0s
info: installing component 'clippy'
info: installing component 'rust-docs'
 14.3 MiB /  14.3 MiB (100 %)   1.2 MiB/s in 16s ETA:  0s
info: installing component 'rust-std'
 23.6 MiB /  23.6 MiB (100 %)   5.3 MiB/s in  4s ETA:  0s
info: installing component 'rustc'
 61.4 MiB /  61.4 MiB (100 %)   6.3 MiB/s in  9s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.75.0 (82e1608df 2023-12-21)
...
```

**Comment by CrotchBurnt** [comment] 2024-01-17 06:25
@rami3l I ran `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` just now, and the error's gone.
```
You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: x86_64-unknown-linux-gnu
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>

info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2023-12-28, rust version 1.75.0 (82e1608df 2023-12-21)
info: downloading component 'cargo'
  7.5 MiB /   7.5 MiB (100 %) 1012.0 KiB/s in  7s ETA:  0s
info: downloading component 'clippy'
  2.1 MiB /   2.1 MiB (100 %)   1.1 MiB/s in  2s ETA:  0s
info: downloading component 'rust-docs'
 14.3 MiB /  14.3 MiB (100 %)   1.1 MiB/s in 13s ETA:  0s
info: downloading component 'rust-std'
 23.6 MiB /  23.6 MiB (100 %)   1.2 MiB/s in 21s ETA:  0s
info: downloading component 'rustc'
 61.4 MiB /  61.4 MiB (100 %)   1.1 MiB/s in 53s ETA:  0sS
info: downloading component 'rustfmt'
  2.3 MiB /   2.3 MiB (100 %)   1.1 MiB/s in  2s ETA:  0s
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 14.3 MiB /  14.3 MiB (100 %)   9.5 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
 23.6 MiB /  23.6 MiB (100 %)  17.4 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 61.4 MiB /  61.4 MiB (100 %)  20.7 MiB/s in  2s ETA:  0s^[[2~
info: installing component 'rustfmt'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.75.0 (82e1608df 2023-12-21)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"

```

**Comment by xen0n** [comment] 2024-01-17 08:30
Thanks for the ping! I've just retried on `riscv64gc-unknown-linux-gnu` and theproblem is gone. Maybe it was just a transient configuration problem that has since been fixed.

**Comment by rami3l** [comment] 2024-01-17 08:57
@CrotchBurnt @xen0n That's interesting. Thanks again for the report!

I'm closing this issue for now, feel free to contact us again when the bug happens again 👀

**Closed as not planned by rami3l** 2024-01-17 08:57 UTC
Labels: bug
