### ISSUE TITLE
Install zsh completions for core tools

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#1089] opened 2017-04-29 14:37 UTC
Everything below is about zsh. I have no idea about bash.

Both `cargo` and `rustc` have completions: [here](https://github.com/rust-lang/cargo/blob/master/src/etc/_cargo) and [here](https://github.com/rust-lang/zsh-config/blob/master/_rust) not even speaking of `rustup`, that can generate its own ones. It took me a good amount of time to find these completions for every project and create them manually. I guess they could and should be installed alongside with the tools, in particular: 

* ask whether the user wants to install completions for core tools
* if yes, ask whether it should be system-wide or local
* if system-wide, install to `/usr/share/zsh/site-functions`, if local, install somewhere in inner directories (`~/.multirust/completions` maybe? not sure) and tell the user to append this path to `$fpath` variable before `compinit` is executed

Also, I'm talking about the bootstrapper from the website `... | sh`. Other types of installations might already do this. But in case they don't, it'd nice to have it there too.

Also, I'm not sure that `rustc` should have `completions` command - this is "one-and-done" and is useless afterwards only stealing attention.

Also, not sure about the debugger and other tools - they may need completions as well.

**Comment by Diggsey** [comment] 2017-05-05 21:40
Dupe of #387

**Closed as completed by Diggsey** 2017-05-05 21:40 UTC
Labels: enhancement
