### ISSUE TITLE
Component conflicts against it's own manifest?

### ISSUE THREAD

**Issue by DasLixou** [rust-lang/rustup#3676] opened 2024-02-19 16:05 UTC
### Problem

Updated rust via `rustup update`.
Got this (shortened) output:
```
info: removing previous version of component 'rustfmt'
warning: during uninstall component rustfmt was not found
info: installing component 'rust-std' for 'x86_64-unknown-none'
info: installing component 'rust-std' for 'thumbv6m-none-eabi'
  9.0 MiB /   9.0 MiB (100 %)   8.7 MiB/s in  1s ETA:  0s
info: installing component 'llvm-tools'
 30.2 MiB /  30.2 MiB (100 %)  11.3 MiB/s in  2s ETA:  0s
info: installing component 'miri'
info: installing component 'rust-src'
info: installing component 'cargo'
info: rolling back changes
error: failed to install component: 'cargo-x86_64-pc-windows-msvc', detected conflict: 'lib/rustlib\manifest-cargo-x86_64-pc-windows-msvc'
info: checking for self-update

         stable-x86_64-pc-windows-msvc updated - rustc 1.76.0 (07dca489a 2024-02-04) (from rustc 1.75.0 (82e1608df 2023-12-21))
  nightly-x86_64-pc-windows-msvc update failed - rustc 1.74.0-nightly (1e746d774 2023-09-07)
```

### Steps

`rustup update` in a dedicated terminal. No rust-analyzer or similar open.

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

wasm32-wasi
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.76.0 (07dca489a 2024-02-04)
```

**Comment by rami3l** [comment] 2024-02-19 16:07
Thanks a lot for filing this issue! I guess it's still an example of #2417 (which eventually leads to #988), unfortunately 😢

We currently have those two issues on our radar and wish to address both in the long run.

**Comment by DasLixou** [comment] 2024-02-19 16:09
> I guess it's still an example of #2417.

huh, i explicitly searched for 'conflict manifest', guess i'm stupid, should i close this?

**Comment by rami3l** [comment] 2024-02-19 16:10
I guess I can close it as a duplicate of #2417. Sorry for the inconvenience!

**Closed as not planned by rami3l** 2024-02-19 16:10 UTC
Labels: bug
