### ISSUE TITLE
add comand for uninstalling all toolchains

### ISSUE THREAD

**Issue by e00E** [rust-lang/rustup#4092] opened 2024-11-20 13:50 UTC
### Problem you are trying to solve

I have many toolchains installed as seen by `rustup toolchain list`. I want to uninstall all of them. This is tedious to do by hand. Also, if you want to do this in an automated fashion, you need to parse rustups output to know which toolchains to uninstall.

### Solution you'd like

A command like `rustup toolchain uninstall-all` that uninstalls all toolchains.

**Comment by rami3l** [comment] 2024-11-25 01:44
Duplicate of #2530.

**Closed as not planned by rami3l** 2024-11-25 01:44 UTC
Labels: enhancement
