### ISSUE TITLE
Deprecation message when installing `stable-x86_64` on x86_64

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rustup#2837] opened 2021-08-07 17:51 UTC
If on an x86_64 system I try `rustup install stable-x86_64`, I get
```
error: DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain as the default.
warning: toolchain 'stable-x86_64' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add x86_64` instead?
```

This looks like a false positive for the deprecation warning to me.

**Notes**

Output of `rustup --version`:
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.54.0 (a178d0322 2021-07-26)`
```

**Comment by ehuss** [comment] 2021-08-07 21:09
I think this was supposed to be fixed by #2782, but it doesn't seem to be a complete fix.  The issue is that [this comparison](https://github.com/rust-lang/rustup/blob/c33cb5ed7fc2854eab7f3cfb1fa6d012b13a8f6c/src/dist/dist.rs#L325-L327) fails because there is no OS in `stable-x86_64`.  I'm not sure, but I would guess that it could assume if os is None to assume it is the host OS?

**Comment by kinnison** [comment] 2021-08-09 12:33
Yes, we had a discussion about this elsewhere, I agree with @ehuss 's analysis.  I think i was assuming by the time this was called the toolchain would be fully resolved.  Instead we need to resolve things explicitly at the callsite, or else in this function.

**Comment by kinnison** [comment] 2021-09-04 10:53
This is also related to #2672

**Closed as completed** 2021-11-11 09:46 UTC
Labels: bug, help wanted, E-easy, E-mentor
