### ISSUE TITLE
'Component unavailable' error is formatted badly

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustup#2648] opened 2021-02-04 19:32 UTC
**Problem**

The error message is missing a newline.

**Steps**
```
> rustup component add miri
error: component 'miri' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel stableIf you don't need the component, you can remove it with:

    rustup component remove --toolchain stable --target x86_64-unknown-linux-gnu miri
```

Also, it seems odd that it suggests uninstalling a component that's not installed.

**Notes**

Output of `rustup --version`:
```
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.49.0 (e1884a8e3 2020-12-29)`
```
Output of `rustup show`:
```
> rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/joshua/.local/lib/rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
... lots of toolchains follow ...

installed targets for active toolchain
--------------------------------------

x86_64-pc-windows-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Comment by danitrod** [comment] 2021-02-05 22:25
Can I work on this? From my understanding the issue is in https://github.com/rust-lang/rustup/blob/master/src/errors.rs, line 428 and 440

**Comment by kinnison** [comment] 2021-02-07 09:29
That looks like the right place to look yes.  There are a couple messages there which might need some attention.

**Comment by danitrod** [comment] 2021-02-07 18:34
Looks like this was already addressed by commit [`b045fb2c9817bb5436651bcfd2584936af4f0f15`](https://github.com/rust-lang/rustup/commit/b045fb2c9817bb5436651bcfd2584936af4f0f15).

**Comment by kinnison** [comment] 2021-02-09 10:47
It's amazing how I can forget things that recent :(  Thank you for finding that @danitrod

**Comment by kinnison** [comment] 2021-04-29 16:31
1.24.1 has now been released and hopefully won't need to be withdrawn.

**Closed as completed by kinnison** 2021-04-29 16:31 UTC
Labels: bug, fixed-next-release
