### ISSUE TITLE
Installing rust-src seems to miss some component

### ISSUE THREAD

**Issue by ylabidi** [rust-lang/rustup#2526] opened 2020-10-17 18:13 UTC
**Problem**
After `rust-src` is seemingly successfully installed, I still get error from emacs/racer about failing to find the sources at the expected path. And sure enough that path doesn't exist:
```
eldoc error: (user-error No such directory:                │
/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src. Please set   ‘racer-rust-src-path’ or ‘RUST_SRC_PATH’)
```
The actual tree there is as follows:
```
$ ls ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/
Cargo.lock  library
```

**Steps**

1. Install `rust-src`
2. edit a rust file with a configured emacs editor
3. emacs keeps complaining about sources not available

**Comment by ehuss** [comment] 2020-10-17 18:57
(Duplicate of #2522.)

The directory was renamed to `library`.  Racer was updated in https://github.com/racer-rust/racer/pull/1130 to use the new directory, but it looks like the README was not updated.  Perhaps file an issue on the racer repo?

EDIT: Or, you may want to check if your installation of racer is out of date, I'm not sure if a new version is available.

**Comment by ylabidi** [comment] 2020-10-17 19:17
Thanks, I'll build racer off the latest source and see if it solves the issue.

**Closed as completed** 2020-10-17 19:20 UTC
Labels: bug

**Comment by ylabidi** [comment] 2020-10-17 19:58
Just an FYI for whoever stumbles on this with a similar configuration (emacs + rustic + rls), it seems updating racer has no effect, because in this case `rls` handles the completion and it uses racer as a library to that effect, and it seems it's still built against an older version of racer.
